<?php

return [
    'teams' => [
        'base_team_code' => 'OCP',
        'tui_team_code' => 'TUI',
    ],
    'push' => [
        'availability_requires_push' => true,
        'fcm_project_id' => env('FCM_PROJECT_ID'),
    ],
    'location' => [
        'default_retention_days' => (int) env('LOCATION_RETENTION_DAYS', 30),
    ],
    'drone_flight' => [
        'aeret_map_url' => env('AERET_DRONE_MAP_URL', 'https://aeret.kaartviewer.nl/?@dpf_basic'),
        'aeret_api_url' => env('AERET_API_URL'),
        'weather_provider' => 'Open-Meteo',
    ],
    'geocoding' => [
        'enabled' => filter_var(env('GEOCODING_ENABLED', true), FILTER_VALIDATE_BOOL),
        'provider' => env('GEOCODING_PROVIDER', 'nominatim'),
        'nominatim_url' => env('GEOCODING_NOMINATIM_URL', 'https://nominatim.openstreetmap.org/search'),
        'user_agent' => env('GEOCODING_USER_AGENT'),
        'country_codes' => env('GEOCODING_COUNTRY_CODES', 'nl,be,de'),
    ],
    'incident_location' => [
        'enabled' => filter_var(env('INCIDENT_LOCATION_ENRICHMENT_ENABLED', true), FILTER_VALIDATE_BOOL),
        'wfs_url' => env('INCIDENT_PROVINCE_WFS_URL', 'https://service.pdok.nl/kadaster/brk-bestuurlijke-gebieden/wfs/v1_0'),
        'country_url' => env('INCIDENT_COUNTRY_GISCO_URL', 'https://gisco-services.ec.europa.eu/id/country'),
        'connect_timeout_seconds' => (int) env('INCIDENT_LOCATION_CONNECT_TIMEOUT_SECONDS', 2),
        'timeout_seconds' => (int) env('INCIDENT_LOCATION_TIMEOUT_SECONDS', 5),
        'backfill_batch' => max(2, min(3, (int) env('INCIDENT_LOCATION_BACKFILL_BATCH', 3))),
    ],
    'dispatch' => [
        'eta_ring_minutes' => (int) env('DISPATCH_ETA_RING_MINUTES', 15),
        'estimated_eta_speed_kmh' => (float) env('DISPATCH_ESTIMATED_ETA_SPEED_KMH', 60),
    ],
    'routing' => [
        'enabled' => filter_var(env('ROUTING_ENABLED', false), FILTER_VALIDATE_BOOL),
        'provider' => env('ROUTING_PROVIDER', 'osrm'),
        'admin_sources' => [
            [
                'id' => 'netherlands',
                'label' => 'Nederland',
                'latest_url' => 'https://download.geofabrik.de/europe/netherlands-latest.osm.pbf',
            ],
            [
                'id' => 'belgium',
                'label' => 'België',
                'latest_url' => 'https://download.geofabrik.de/europe/belgium-latest.osm.pbf',
            ],
        ],
        'admin_status_path' => env('OSRM_ADMIN_STATUS_PATH', '/var/log/dis/osrm-status.json'),
        'admin_state_root' => env('OSRM_ADMIN_STATE_ROOT', rtrim((string) env('DIS_DATA_PATH', '/opt/dis-data'), '/').'/osrm-admin'),
        'admin_health_coordinate' => [
            'longitude' => 5.1214,
            'latitude' => 52.0907,
        ],
        'cache_ttl_seconds' => (int) env('ROUTING_CACHE_TTL_SECONDS', 900),
        'failure_cache_ttl_seconds' => (int) env('ROUTING_FAILURE_CACHE_TTL_SECONDS', 15),
        'fallback_speed_kmh' => (float) env('ROUTING_FALLBACK_SPEED_KMH', env('DISPATCH_ESTIMATED_ETA_SPEED_KMH', 60)),
        'osrm' => [
            'base_url' => env('OSRM_BASE_URL'),
            'allowed_hosts' => env('OSRM_ALLOWED_HOSTS', '127.0.0.1,localhost,::1'),
            'profile' => env('OSRM_PROFILE', 'driving'),
            'connect_timeout_seconds' => (int) env('OSRM_CONNECT_TIMEOUT_SECONDS', 1),
            'timeout_seconds' => (int) env('OSRM_TIMEOUT_SECONDS', 3),
            'batch_size' => (int) env('OSRM_BATCH_SIZE', 50),
            'geometry_max_routes' => (int) env('OSRM_GEOMETRY_MAX_ROUTES', 25),
            'geometry_concurrency' => (int) env('OSRM_GEOMETRY_CONCURRENCY', 10),
        ],
    ],
    'updates' => [
        'android_application_id' => env('ANDROID_APPLICATION_ID', 'nl.wrdmarco.dis'),
        'application_estimated_duration_seconds' => (int) env('APPLICATION_UPDATE_ESTIMATED_DURATION_SECONDS', 900),
        'system_estimated_duration_seconds' => (int) env('SYSTEM_UPDATE_ESTIMATED_DURATION_SECONDS', 1500),
    ],
    'system_metrics' => [
        'disk_path' => env('DIS_DATA_PATH', '/opt/dis-data'),
    ],
    'knmi_forecast' => [
        'api_base_url' => 'https://api.dataplatform.knmi.nl/open-data/v1',
        'download_host' => 'knmi-kdp-datasets-eu-west-1.s3.eu-west-1.amazonaws.com',
        'dataset' => 'harmonie_arome_cy43_p1',
        'dataset_version' => '1.0',
        'api_key' => env('KNMI_OPEN_DATA_API_KEY'),
        'storage_root' => env('KNMI_FORECAST_STORAGE_ROOT', storage_path('app/knmi-forecast')),
        'minimum_archive_bytes' => (int) env('KNMI_FORECAST_MIN_ARCHIVE_BYTES', 104857600),
        'maximum_archive_bytes' => (int) env('KNMI_FORECAST_MAX_ARCHIVE_BYTES', 1181116006),
        'download_timeout_seconds' => (int) env('KNMI_FORECAST_DOWNLOAD_TIMEOUT_SECONDS', 1800),
        'connect_timeout_seconds' => (int) env('KNMI_FORECAST_CONNECT_TIMEOUT_SECONDS', 10),
        'retain_releases' => (int) env('KNMI_FORECAST_RETAIN_RELEASES', 2),
        'maximum_model_age_seconds' => (int) env('KNMI_FORECAST_MAXIMUM_MODEL_AGE_SECONDS', 21600),
        'maximum_valid_offset_seconds' => (int) env('KNMI_FORECAST_MAXIMUM_VALID_OFFSET_SECONDS', 3600),
        'integrity_cache_seconds' => (int) env('KNMI_FORECAST_INTEGRITY_CACHE_SECONDS', 900),
        'point_cache_seconds' => (int) env('KNMI_FORECAST_POINT_CACHE_SECONDS', 21600),
        'query_timeout_seconds' => (int) env('KNMI_FORECAST_QUERY_TIMEOUT_SECONDS', 10),
    ],
    'knmi_precipitation' => [
        'api_base_url' => 'https://api.dataplatform.knmi.nl/open-data/v1',
        'download_host' => 'knmi-kdp-datasets-eu-west-1.s3.eu-west-1.amazonaws.com',
        'storage_root' => env(
            'KNMI_PRECIPITATION_STORAGE_ROOT',
            rtrim((string) env('KNMI_FORECAST_STORAGE_ROOT', storage_path('app/knmi-forecast')), '/\\').'/precipitation-outlook',
        ),
        'radar_dataset' => 'radar_forecast',
        'radar_version' => '2.0',
        'radar_minimum_bytes' => (int) env('KNMI_PRECIPITATION_RADAR_MINIMUM_BYTES', 32_768),
        'radar_maximum_bytes' => (int) env('KNMI_PRECIPITATION_RADAR_MAXIMUM_BYTES', 16_777_216),
        'probability_dataset' => 'seamless_precipitation_ensemble_forecast_probabilities',
        'probability_version' => '1.0',
        'probability_minimum_bytes' => (int) env('KNMI_PRECIPITATION_PROBABILITY_MINIMUM_BYTES', 1_048_576),
        'probability_maximum_bytes' => (int) env('KNMI_PRECIPITATION_PROBABILITY_MAXIMUM_BYTES', 134_217_728),
        'connect_timeout_seconds' => (int) env('KNMI_PRECIPITATION_CONNECT_TIMEOUT_SECONDS', 10),
        'download_timeout_seconds' => (int) env('KNMI_PRECIPITATION_DOWNLOAD_TIMEOUT_SECONDS', 180),
        'retain_releases' => (int) env('KNMI_PRECIPITATION_RETAIN_RELEASES', 2),
        'maximum_reference_age_seconds' => (int) env('KNMI_PRECIPITATION_MAXIMUM_REFERENCE_AGE_SECONDS', 1200),
        'integrity_cache_seconds' => (int) env('KNMI_PRECIPITATION_INTEGRITY_CACHE_SECONDS', 300),
        'point_cache_seconds' => (int) env('KNMI_PRECIPITATION_POINT_CACHE_SECONDS', 600),
        'query_timeout_seconds' => (int) env('KNMI_PRECIPITATION_QUERY_TIMEOUT_SECONDS', 10),
    ],
    'eumetsat_lightning' => [
        // EUMETView exposes this WMS without an account, token or API key. Keep
        // the remote contract fixed so a configuration change cannot turn the
        // scheduled importer into a generic outbound request primitive.
        'endpoint' => 'https://view.eumetsat.int/geoserver/wms',
        'layer' => 'mtg_fd:li_afa',
        'style' => 'mtg_li_afa',
        'crs' => 'CRS:84',
        'bbox' => [2.5, 50.5, 7.8, 53.7],
        'frame_width' => 640,
        'frame_height' => 384,
        'frame_count' => 7,
        'interval_minutes' => 5,
        'atlas_columns' => 4,
        'atlas_rows' => 2,
        'storage_root' => env(
            'EUMETSAT_LIGHTNING_STORAGE_ROOT',
            rtrim((string) env('DIS_DATA_PATH', '/opt/dis-data'), '/\\').'/webapp/backend/storage/app/eumetsat-lightning',
        ),
        'connect_timeout_seconds' => 5,
        'capabilities_timeout_seconds' => 15,
        'frame_timeout_seconds' => 20,
        'maximum_capabilities_bytes' => 1_048_576,
        'maximum_frame_bytes' => 4_194_304,
        'maximum_atlas_bytes' => 33_554_432,
        'maximum_age_seconds' => 900,
        'retain_releases' => 2,
        'source_name' => 'EUMETSAT MTG Lightning Imager',
        'source_url' => 'https://view.eumetsat.int/',
        'license_name' => 'EUMETSAT Data Policy (vrije EUMETView-toegang)',
        'license_url' => 'https://www.eumetsat.int/eumetsat-data-policy',
    ],
    'wallboards' => [
        'pairing_ttl_seconds' => (int) env('WALLBOARD_PAIRING_TTL_SECONDS', 300),
        'credential_cookie_days' => (int) env('WALLBOARD_CREDENTIAL_COOKIE_DAYS', 365),
        'rotation_hours' => (int) env('WALLBOARD_SESSION_ROTATION_HOURS', 12),
        'rotation_grace_seconds' => (int) env('WALLBOARD_SESSION_ROTATION_GRACE_SECONDS', 120),
        'touch_interval_seconds' => (int) env('WALLBOARD_SESSION_TOUCH_INTERVAL_SECONDS', 60),
        'ticker_connect_timeout_seconds' => (int) env('WALLBOARD_TICKER_CONNECT_TIMEOUT_SECONDS', 2),
        'ticker_timeout_seconds' => (int) env('WALLBOARD_TICKER_TIMEOUT_SECONDS', 4),
        'ticker_cache_seconds' => (int) env('WALLBOARD_TICKER_CACHE_SECONDS', 300),
        'ticker_failure_cache_seconds' => (int) env('WALLBOARD_TICKER_FAILURE_CACHE_SECONDS', 60),
        'uav_forecast' => [
            'connect_timeout_seconds' => (int) env('WALLBOARD_UAV_FORECAST_CONNECT_TIMEOUT_SECONDS', 2),
            'timeout_seconds' => (int) env('WALLBOARD_UAV_FORECAST_TIMEOUT_SECONDS', 5),
            'cache_seconds' => (int) env('WALLBOARD_UAV_FORECAST_CACHE_SECONDS', 900),
            'last_good_cache_seconds' => (int) env('WALLBOARD_UAV_FORECAST_LAST_GOOD_CACHE_SECONDS', 21600),
            'geocode_cache_seconds' => (int) env('WALLBOARD_UAV_FORECAST_GEOCODE_CACHE_SECONDS', 2592000),
            'weather_stale_seconds' => (int) env('WALLBOARD_UAV_FORECAST_WEATHER_STALE_SECONDS', 1800),
            'kp_stale_seconds' => (int) env('WALLBOARD_UAV_FORECAST_KP_STALE_SECONDS', 14400),
            'knmi_edr_api_key' => env('KNMI_EDR_API_KEY'),
            'cloud_base_station_cache_seconds' => (int) env('WALLBOARD_UAV_CLOUD_BASE_STATION_CACHE_SECONDS', 86400),
            'cloud_base_stale_seconds' => (int) env('WALLBOARD_UAV_CLOUD_BASE_STALE_SECONDS', 1800),
            'cloud_base_max_distance_km' => (float) env('WALLBOARD_UAV_CLOUD_BASE_MAX_DISTANCE_KM', 30),
            // Application-owned reference points: one stable sample in every Dutch
            // province. National forecasts never depend on twelve geocoder calls.
            'province_reference_points' => [
                ['label' => 'Drenthe', 'latitude' => 52.9928, 'longitude' => 6.5642],
                ['label' => 'Flevoland', 'latitude' => 52.5185, 'longitude' => 5.4714],
                ['label' => 'Friesland', 'latitude' => 53.2012, 'longitude' => 5.7999],
                ['label' => 'Gelderland', 'latitude' => 51.9851, 'longitude' => 5.8987],
                ['label' => 'Groningen', 'latitude' => 53.2194, 'longitude' => 6.5665],
                ['label' => 'Limburg', 'latitude' => 50.8514, 'longitude' => 5.6910],
                ['label' => 'Noord-Brabant', 'latitude' => 51.6978, 'longitude' => 5.3037],
                ['label' => 'Noord-Holland', 'latitude' => 52.3874, 'longitude' => 4.6462],
                ['label' => 'Overijssel', 'latitude' => 52.5168, 'longitude' => 6.0830],
                ['label' => 'Utrecht', 'latitude' => 52.0907, 'longitude' => 5.1214],
                ['label' => 'Zeeland', 'latitude' => 51.4988, 'longitude' => 3.6100],
                ['label' => 'Zuid-Holland', 'latitude' => 52.0705, 'longitude' => 4.3007],
            ],
            'thresholds' => [
                // Conservatieve operationele defaults; toestel-, missie- en lokale limieten gaan altijd voor.
                'temperature_c' => [
                    'green_min' => (float) env('WALLBOARD_UAV_TEMPERATURE_GREEN_MIN_C', 0),
                    'green_max' => (float) env('WALLBOARD_UAV_TEMPERATURE_GREEN_MAX_C', 35),
                    'orange_min' => (float) env('WALLBOARD_UAV_TEMPERATURE_ORANGE_MIN_C', -10),
                    'orange_max' => (float) env('WALLBOARD_UAV_TEMPERATURE_ORANGE_MAX_C', 45),
                ],
                'dew_point_c' => [
                    'green_spread_min' => (float) env('WALLBOARD_UAV_DEW_POINT_GREEN_SPREAD_MIN_C', 3),
                    'orange_spread_min' => (float) env('WALLBOARD_UAV_DEW_POINT_ORANGE_SPREAD_MIN_C', 1.5),
                ],
                'wind_speed_kmh' => [
                    'green_max' => (float) env('WALLBOARD_UAV_WIND_GREEN_MAX_KMH', 20),
                    'orange_max' => (float) env('WALLBOARD_UAV_WIND_ORANGE_MAX_KMH', 30),
                ],
                'wind_gust_kmh' => [
                    'green_max' => (float) env('WALLBOARD_UAV_GUST_GREEN_MAX_KMH', 30),
                    'orange_max' => (float) env('WALLBOARD_UAV_GUST_ORANGE_MAX_KMH', 45),
                ],
                'precipitation_mm' => [
                    'green_max' => (float) env('WALLBOARD_UAV_PRECIPITATION_GREEN_MAX_MM', 0),
                    'orange_max' => (float) env('WALLBOARD_UAV_PRECIPITATION_ORANGE_MAX_MM', 0.5),
                ],
                'precipitation_probability_pct' => [
                    'green_max' => (float) env('WALLBOARD_UAV_PRECIPITATION_PROBABILITY_GREEN_MAX_PCT', 20),
                    'orange_max' => (float) env('WALLBOARD_UAV_PRECIPITATION_PROBABILITY_ORANGE_MAX_PCT', 50),
                ],
                'cloud_cover_pct' => [
                    'green_max' => (float) env('WALLBOARD_UAV_CLOUD_COVER_GREEN_MAX_PCT', 50),
                    'orange_max' => (float) env('WALLBOARD_UAV_CLOUD_COVER_ORANGE_MAX_PCT', 85),
                ],
                'visibility_m' => [
                    'green_min' => (float) env('WALLBOARD_UAV_VISIBILITY_GREEN_MIN_M', 5000),
                    'orange_min' => (float) env('WALLBOARD_UAV_VISIBILITY_ORANGE_MIN_M', 2000),
                ],
                'kp_index' => [
                    'green_max_exclusive' => (float) env('WALLBOARD_UAV_KP_GREEN_MAX_EXCLUSIVE', 4),
                    'orange_max_exclusive' => (float) env('WALLBOARD_UAV_KP_ORANGE_MAX_EXCLUSIVE', 6),
                ],
            ],
        ],
    ],
    'speech' => [
        'locale' => 'nl-NL',
        'socket_path' => env('SPEECH_ENGINE_SOCKET', '/run/dis-tts/engine.sock'),
        'protocol_version' => 1,
        'connect_timeout_seconds' => (float) env('SPEECH_ENGINE_CONNECT_TIMEOUT_SECONDS', 1),
        'synthesis_timeout_seconds' => max(300, (int) env('SPEECH_ENGINE_SYNTHESIS_TIMEOUT_SECONDS', 14_400)),
        'install_timeout_seconds' => max(300, (int) env('SPEECH_ENGINE_INSTALL_TIMEOUT_SECONDS', 14_400)),
        'install_poll_interval_seconds' => max(1, (int) env('SPEECH_ENGINE_INSTALL_POLL_INTERVAL_SECONDS', 2)),
        'maximum_request_bytes' => 65_536,
        'maximum_response_bytes' => 262_144,
        'data_root' => env('SPEECH_DATA_ROOT', '/opt/dis-data/tts'),
        'cache_root' => env('SPEECH_CACHE_ROOT', '/opt/dis-data/tts/cache'),
        'staging_root' => env('SPEECH_STAGING_ROOT', '/opt/dis-data/tts/staging'),
        'voice_root' => storage_path('app/speech/voices'),
        'cache_hmac_key' => env('SPEECH_CACHE_HMAC_KEY'),
        'cache_key_version' => 1,
        'cache_quota_bytes' => max(268_435_456, (int) env('SPEECH_CACHE_QUOTA_BYTES', 5_368_709_120)),
        'segment_retention_days' => max(1, (int) env('SPEECH_SEGMENT_RETENTION_DAYS', 30)),
        'composite_retention_days' => max(1, (int) env('SPEECH_COMPOSITE_RETENTION_DAYS', 7)),
        'preview_retention_hours' => max(1, (int) env('SPEECH_PREVIEW_RETENTION_HOURS', 24)),
        'release_gate_seconds' => 10,
        'ffmpeg_binary' => env('SPEECH_FFMPEG_BINARY', '/usr/bin/ffmpeg'),
        'ffprobe_binary' => env('SPEECH_FFPROBE_BINARY', '/usr/bin/ffprobe'),
        'models' => [
            'chatterbox_multilingual_v3' => [
                'name' => 'Chatterbox Multilingual V3',
                'description' => 'Hoogwaardige meertalige spraaksynthese met stemklonen.',
                'parameter_count' => 500_000_000,
                'download_bytes' => 3_208_951_924,
                'license_spdx' => 'MIT',
                'commercial_use' => true,
                'supported_languages' => ['nl-NL'],
                'capabilities' => ['voice_clone' => true, 'voice_design' => false, 'speed_control' => false],
                'built_in_voice_design_revision' => null,
                'cpu' => [
                    'supported' => true,
                    'recommended_ram_bytes' => 17_179_869_184,
                    'note' => 'CPU-uitvoering is mogelijk, maar haalt mogelijk de alarmdeadline niet; lokale noodspraak blijft leidend.',
                ],
                'revision' => '5bb1f6ee58e50c3b8d408bc82a6d3740c2db6e18',
                'weights_sha256' => 'f4f54a01de9d1354e282eab28a15ffeabac9d87d5f3a28fe72ed2548e9cd2286',
            ],
            'voxcpm2' => [
                'name' => 'VoxCPM2',
                'description' => 'Hoogwaardig 2B-model voor meertalige spraaksynthese en stemklonen.',
                'parameter_count' => 2_000_000_000,
                'download_bytes' => 4_960_722_408,
                'license_spdx' => 'Apache-2.0',
                'commercial_use' => true,
                'supported_languages' => ['nl-NL'],
                'capabilities' => ['voice_clone' => true, 'voice_design' => true, 'speed_control' => false],
                'built_in_voice_design_revision' => 'voxcpm2-nl-nl-female-pa-v1',
                'cpu' => [
                    'supported' => true,
                    'recommended_ram_bytes' => 34_359_738_368,
                    'note' => 'Door de 2B-omvang is ruime RAM-capaciteit nodig; genereer vooraf en vertrouw bij deadline op lokale noodspraak.',
                ],
                'revision' => 'bffb3df5a29440629464e5e839f4d214c8714c3d',
                'weights_sha256' => 'acee75a3e2125be4089f81fa8259372a797e87c799ab13dad27ce38fd385e126',
            ],
        ],
    ],
    'retention' => [
        'push_logs_days' => (int) env('PUSH_LOG_RETENTION_DAYS', 90),
        'audit_logs_days' => (int) env('AUDIT_LOG_RETENTION_DAYS', 3650),
    ],
];
