import type { ManualGuideMap } from '../manualTypes';

export const accountManualGuides = {
  navigation: [
    {
      id: 'navigation-open-section',
      title: 'Een onderdeel openen',
      intro: 'Ga vanaf elk scherm naar het onderdeel dat je nodig hebt.',
      steps: [
        { label: 'Open het menu', description: 'Op een computer staat het menu links. Op een telefoon kies je linksboven de knop met de drie strepen.' },
        { label: 'Kies een groep', description: 'Zoek de juiste groep, bijvoorbeeld Operatie, Mensen en middelen of Beheer.' },
        { label: 'Kies het onderdeel', description: 'Klik op de naam van het onderdeel. Bovenaan verschijnt daarna de titel van de geopende pagina.' },
        { label: 'Ga terug met het menu', description: 'Je hoeft de terugknop van de browser niet te gebruiken. Kies gewoon een ander onderdeel in hetzelfde menu.' },
      ],
      result: 'Het gekozen onderdeel is geopend. Onderdelen waarvoor je geen rechten hebt, horen niet in jouw menu te staan.',
    },
    {
      id: 'navigation-account-menu',
      title: 'Het accountmenu gebruiken',
      intro: 'Open je profiel, Help, de kleurweergave of meld je af.',
      steps: [
        { label: 'Klik rechtsboven op je naam', description: 'Het accountmenu klapt onder je naam en e-mailadres open.' },
        { label: 'Kies een actie', description: 'Kies Profiel, Help, Lichte modus of Donkere modus, of Uitloggen.' },
        { label: 'Sluit zonder keuze', description: 'Klik buiten het menu of druk op Escape wanneer je niets wilt wijzigen.' },
      ],
      result: 'De gekozen accountactie wordt uitgevoerd. Je kleurkeuze wordt voor een volgend bezoek onthouden.',
    },
  ],
  'account-access': [
    {
      id: 'account-finish-invitation',
      title: 'Een uitnodiging afronden',
      intro: 'Maak je account gebruiksklaar via de persoonlijke uitnodigingslink.',
      prerequisites: ['Gebruik de nieuwste uitnodigingsmail.', 'Een uitnodigingslink is 60 minuten geldig.'],
      steps: [
        { label: 'Open de uitnodigingslink', description: 'Klik in de ontvangen e-mail op de registratielink. Deel deze link niet met iemand anders.' },
        { label: 'Maak je wachtwoord', description: 'Vul Wachtwoord en Wachtwoord bevestigen in en kies Account activeren.' },
        { label: 'Rond MFA af wanneer dit verschijnt', description: 'Scan de QR-code met je beveiligingsapp, vul de actuele zescijferige MFA-code in en kies MFA activeren.' },
        { label: 'Kies Android of iOS', description: 'Open vanuit de wizard de juiste app-link, installeer de operator-app en open daarin de QR-scanner.' },
        { label: 'Koppel de app', description: 'Maak in de wizard een persoonlijke koppel-QR en scan deze direct met de operator-app. De QR is eenmalig en 30 seconden geldig.' },
        { label: 'Rond de wizard af', description: 'Doorloop alleen de stappen voor apps waartoe je toegang hebt en kies uiteindelijk Naar D.I.S.' },
        { label: 'Vul ontbrekende profielgegevens aan', description: 'Verschijnt Vul je gegevens aan, vul dan voornaam, achternaam, internationaal telefoonnummer, land en woonplaats in. Voor Nederland en België is ook provincie of regio nodig.' },
      ],
      result: 'Je account wordt actief en de gekozen mobiele app is met de persoonlijke QR-code veilig gekoppeld.',
      warning: 'Is de link verlopen, vraag dan een beheerder om de uitnodiging opnieuw te versturen.',
    },
    {
      id: 'account-sign-in-help',
      title: 'Aanmelden en problemen oplossen',
      intro: 'Volg deze volgorde wanneer aanmelden niet meteen lukt.',
      steps: [
        { label: 'Vul e-mailadres en wachtwoord in', description: 'Gebruik het e-mailadres waarop je bent uitgenodigd en kies Inloggen.' },
        { label: 'Vul zo nodig de beveiligingscode in', description: 'Open je beveiligingsapp en gebruik de actuele code. Een oude code werkt niet.' },
        { label: 'Wacht bij een tijdelijke blokkade', description: 'Na vijf verkeerde wachtwoorden wacht je vijf minuten. Na vijf verkeerde beveiligingscodes begin je opnieuw bij het aanmeldscherm.' },
        { label: 'Controleer onderhoud', description: 'Zie je het onderhoudsscherm, wacht dan. De pagina controleert ongeveer elke twintig seconden vanzelf opnieuw.' },
        { label: 'Vraag hulp bij een accountblokkade', description: 'Bij Geschorst of Geblokkeerd moet een beheerder je account controleren.' },
      ],
      result: 'Na een geldige aanmelding opent DIS het eerste onderdeel waarvoor je toegang hebt.',
      warning: 'Blijf niet snel achter elkaar codes proberen. Daarmee verleng je het probleem en kan het account opnieuw tijdelijk worden geblokkeerd.',
    },
  ],
  profile: [
    {
      id: 'profile-update-details',
      title: 'Persoonsgegevens aanpassen',
      intro: 'Werk je naam, telefoonnummer of woonplaats zelf bij.',
      steps: [
        { label: 'Open Profiel', description: 'Klik rechtsboven op je naam en kies Profiel.' },
        { label: 'Wijzig de velden', description: 'Pas voornaam, achternaam, telefoonnummer, land, woonplaats en provincie of regio aan. Het e-mailadres is hier alleen zichtbaar.' },
        { label: 'Controleer het telefoonnummer', description: 'Gebruik een internationaal nummer, bijvoorbeeld +31 of +32.' },
        { label: 'Sla de gegevens op', description: 'Kies Gegevens opslaan en wacht op de bevestiging.' },
      ],
      result: 'De nieuwe profielgegevens worden gebruikt in de webapp, het adresboek en bij globale woonplaatsweergave.',
    },
    {
      id: 'profile-plan-availability',
      title: 'Beschikbaarheid per dagdeel plannen',
      intro: 'Stel je vaste week in en maak afwijkingen voor de komende twee weken.',
      steps: [
        { label: 'Open Mijn beschikbaarheid', description: 'Ga op Profiel naar het blok Mijn beschikbaarheid en kies Dagdelen plannen.' },
        { label: 'Stel vaste weekdagen in', description: 'Klik per weekdag op Ochtend, Middag of Avond. Aan betekent standaard beschikbaar; Uit betekent standaard niet beschikbaar.' },
        { label: 'Sla het vaste patroon op', description: 'Kies Vaste dagdelen opslaan. Dit patroon geldt voor toekomstige weken.' },
        { label: 'Plan een afwijkende datum', description: 'Ga in hetzelfde venster naar 2 weken vooruit plannen en klik bij de gewenste datum op het dagdeel.' },
        { label: 'Controleer de nieuwe stand', description: 'Een afwijkende datum wordt direct opgeslagen en gaat voor het vaste weekpatroon.' },
      ],
      result: 'DIS gebruikt per dagdeel eerst een datumafwijking en anders je vaste weekpatroon.',
      warning: 'De knoppen bij de komende twee weken slaan direct op. Alleen het vaste weekpatroon heeft de aparte knop Vaste dagdelen opslaan. Een datumafwijking kan nu niet worden gewist om weer automatisch op het vaste patroon terug te vallen.',
    },
    {
      id: 'profile-manage-own-resources',
      title: 'Een eigen middel of certificaat bijhouden',
      intro: 'Houd operationele gegevens actueel wanneer je hiervoor invoervelden op Profiel ziet.',
      steps: [
        { label: 'Kies het juiste blok', description: 'Ga naar Mijn assets voor een middel of Mijn certificaten voor een bevoegdheid.' },
        { label: 'Vul de gevraagde gegevens in', description: 'Kies bij een drone ook het dronetype. Vul bij een certificaat minimaal soort en afgiftedatum in.' },
        { label: 'Sla de invoer op', description: 'Gebruik de primaire opslagknop onder het formulier.' },
        { label: 'Pas een bestaand item aan', description: 'Kies Aanpassen in de tabel, wijzig de gegevens en sla opnieuw op.' },
        { label: 'Begin een nieuw item', description: 'Kies Nieuw wanneer het formulier nog een bestaand item toont.' },
      ],
      result: 'Het middel of certificaat staat bij je profiel en kan worden gebruikt voor inzetcontrole.',
      warning: 'Verwijder alleen een registratie die echt niet meer bij jou hoort. Een verlopen certificaat laat je bij voorkeur staan met de juiste verloopdatum.',
    },
    {
      id: 'profile-enable-mfa',
      title: 'Tweestapsverificatie instellen',
      intro: 'Beveilig je account met een wisselende zescijferige code.',
      steps: [
        { label: 'Ga naar Multi-factor authenticatie', description: 'Open Profiel en zoek het blok Multi-factor authenticatie.' },
        { label: 'Kies MFA instellen', description: 'DIS toont een QR-code en een geheime sleutel.' },
        { label: 'Scan met je beveiligingsapp', description: 'Voeg een nieuw account toe in bijvoorbeeld je Authenticator-app en scan de QR-code.' },
        { label: 'Vul de zescijferige code in', description: 'Gebruik de code die je beveiligingsapp op dat moment toont.' },
        { label: 'Kies MFA bevestigen', description: 'Wacht tot DIS meldt dat MFA actief is.' },
      ],
      result: 'Bij een volgende aanmelding kan DIS naast je wachtwoord ook de beveiligingscode vragen.',
      warning: 'Worden herstelcodes getoond, bewaar deze dan direct buiten DIS. Verplichte MFA kun je niet zelf uitzetten.',
    },
  ],
  'mobile-app': [
    {
      id: 'mobile-pair-qr',
      title: 'Een mobiele app koppelen met QR-code',
      intro: 'Koppel de operator- of admin-app zonder gebruikersnaam en wachtwoord.',
      mobileApp: 'any',
      prerequisites: ['Installeer de juiste mobiele app.', 'Sta cameragebruik toe wanneer de app daarom vraagt.'],
      steps: [
        { label: 'Open Mijn toestellen', description: 'Ga in de webapp naar Profiel en kies bij Mijn toestellen de knop Toestel toevoegen.' },
        { label: 'Kies de app', description: 'Selecteer Operator-app of Admin-app. Je ziet alleen de apps waarvoor je rol toegang heeft.' },
        { label: 'Open de scanner', description: 'Open in de mobiele app de functie om een QR-koppelcode te scannen.' },
        { label: 'Scan de zichtbare code', description: 'Richt de camera op de QR-code in de webapp. Iedere code is 30 seconden geldig en het webvenster maakt automatisch een nieuwe.' },
        { label: 'Geef het toestel een naam', description: 'Vul in de mobiele app een herkenbare naam in, bijvoorbeeld Prive telefoon of Meldkamertablet.' },
        { label: 'Controleer Mijn toestellen', description: 'Na koppelen verschijnt het toestel in de lijst op je profiel.' },
      ],
      result: 'De app blijft onder jouw account aangemeld. Nadat de app het toestel en push heeft geregistreerd, verschijnt het bij Mijn toestellen.',
      warning: 'Scan altijd de code die op dat moment zichtbaar is. Een verlopen code wordt geweigerd.',
    },
    {
      id: 'mobile-pair-same-device',
      title: 'Koppelen op dezelfde telefoon',
      intro: 'Gebruik de knop of de handmatige gegevens wanneer je de QR-code niet kunt scannen.',
      mobileApp: 'any',
      steps: [
        { label: 'Open Toestel toevoegen', description: 'Open Profiel in de browser op je telefoon en kies Toestel toevoegen.' },
        { label: 'Kies Open app en koppel dit toestel', description: 'De mobiele app wordt geopend met server en koppelcode.' },
        { label: 'Gebruik zo nodig Handmatig koppelen', description: 'Werkt de knop niet, neem dan in de mobiele app de Server en Koppelcode over uit het webvenster.' },
        { label: 'Rond de toestelgegevens af', description: 'Controleer het toesteltype en geef het toestel een herkenbare naam.' },
      ],
      result: 'Het toestel verschijnt bij Mijn toestellen zonder dat een tweede scherm nodig is.',
    },
    {
      id: 'mobile-remove-device',
      title: 'Een gekoppeld toestel verwijderen',
      intro: 'Trek toegang in wanneer een toestel weg, vervangen of niet meer vertrouwd is.',
      steps: [
        { label: 'Open Mijn toestellen', description: 'Ga naar Profiel en zoek het juiste toestel op naam, type en laatste contact.' },
        { label: 'Kies Verwijderen', description: 'DIS opent het venster Toestel verwijderen?.' },
        { label: 'Controleer de toestelnaam', description: 'Zorg dat je niet per ongeluk je huidige of een operationeel gebruikt toestel verwijdert.' },
        { label: 'Bevestig verwijderen', description: 'Kies de rode verwijderknop in het bevestigingsvenster.' },
      ],
      result: 'De mobiele sessie en toestelregistratie worden direct ingetrokken. De verwijderde app moet opnieuw worden gekoppeld.',
      warning: 'Wanneer geen actief app-toestel overblijft, kan DIS push uitschakelen en je op niet beschikbaar zetten.',
    },
  ],
  calendar: [
    {
      id: 'calendar-view-events',
      title: 'Een agenda-item bekijken',
      intro: 'Bekijk trainingen, open dagen en teammomenten.',
      steps: [
        { label: 'Open Agenda', description: 'Kies Agenda in het menu.' },
        { label: 'Ga naar Geplande items', description: 'De tabel toont datum, type, titel, locatie, team en wie het item heeft aangemaakt.' },
        { label: 'Controleer het team', description: 'Iedereen betekent dat het item algemeen is. Anders staat de naam van het betreffende team in de rij.' },
      ],
      result: 'Je weet wanneer en waar het moment plaatsvindt. De mobiele app toont dezelfde agenda alleen-lezen.',
    },
    {
      id: 'calendar-add-event',
      title: 'Een agenda-item toevoegen',
      intro: 'Plan een training, open dag of ander gezamenlijk moment.',
      permissions: ['settings.manage'],
      steps: [
        { label: 'Open Agenda-item toevoegen', description: 'Op de pagina Agenda staat voor beheerders het formulier Agenda-item toevoegen.' },
        { label: 'Vul titel en start in', description: 'Titel en Start zijn verplicht. Kies daarnaast Type en zo nodig Einde en Locatie.' },
        { label: 'Kies de doelgroep', description: 'Laat Team op Iedereen staan voor een algemeen item of kies een specifiek team.' },
        { label: 'Voeg uitleg toe', description: 'Gebruik Omschrijving voor informatie die deelnemers vooraf nodig hebben.' },
        { label: 'Kies Toevoegen', description: 'Wacht op de melding dat het agenda-item is opgeslagen.' },
      ],
      result: 'Het item verschijnt bij Geplande items en wordt zichtbaar in webapp en mobiele agenda.',
    },
    {
      id: 'calendar-delete-event',
      title: 'Een agenda-item verwijderen',
      intro: 'Haal een moment weg dat niet meer doorgaat.',
      permissions: ['settings.manage'],
      steps: [
        { label: 'Zoek het item', description: 'Ga in Agenda naar de tabel Geplande items.' },
        { label: 'Controleer datum en titel', description: 'Controleer goed dat je de juiste rij hebt.' },
        { label: 'Kies Verwijderen', description: 'Gebruik de knop in de kolom Actie.' },
      ],
      result: 'Het agenda-item verdwijnt direct uit de webapp en mobiele agenda.',
      warning: 'Er is geen aparte wijzigknop en geen herstelknop. Bij een fout moet je het item opnieuw toevoegen.',
    },
  ],
} satisfies ManualGuideMap;
