import type { ManualGuideMap } from '../manualTypes';

export const accountManualGuides = {
  navigation: [
    {
      id: 'navigation-open-section',
      title: 'Een onderdeel openen',
      intro: 'Ga vanaf elk scherm naar het onderdeel dat je nodig hebt.',
      steps: [
        { label: 'Open het menu', description: 'Op een computer staat het menu links. Op een telefoon kies je linksboven de knop met de drie strepen.' },
        { label: 'Kies een groep', description: 'Zoek de juiste groep, bijvoorbeeld Operatie, Mensen en middelen of Beheer.' },
        { label: 'Kies het onderdeel', description: 'Klik op de naam van het onderdeel. Bovenaan verschijnt daarna de titel van de geopende pagina.' },
        { label: 'Ga terug met het menu', description: 'Je hoeft de terugknop van de browser niet te gebruiken. Kies gewoon een ander onderdeel in hetzelfde menu.' },
      ],
      result: 'Het gekozen onderdeel is geopend. Onderdelen waarvoor je geen rechten hebt, horen niet in jouw menu te staan.',
    },
    {
      id: 'navigation-account-menu',
      title: 'Het accountmenu gebruiken',
      intro: 'Open je profiel, Help, de kleurweergave of meld je af.',
      steps: [
        { label: 'Klik rechtsboven op je naam', description: 'Het accountmenu klapt onder je naam en e-mailadres open.' },
        { label: 'Kies een actie', description: 'Kies Profiel, Help, Lichte modus of Donkere modus, of Uitloggen.' },
        { label: 'Sluit zonder keuze', description: 'Klik buiten het menu of druk op Escape wanneer je niets wilt wijzigen.' },
      ],
      result: 'De gekozen accountactie wordt uitgevoerd. Je kleurkeuze wordt voor een volgend bezoek onthouden.',
    },
    {
      id: 'navigation-personal-notifications',
      title: 'Persoonlijke meldingen bekijken',
      intro: 'Bekijk updates die specifiek voor jouw account bestemd zijn.',
      steps: [
        { label: 'Let op het bel-icoon', description: 'Bij een nieuwe melding beweegt de bel en loopt het aantal ongelezen meldingen op.' },
        { label: 'Open de meldingen', description: 'Klik rechtsboven op de bel om de nieuwste persoonlijke meldingen te bekijken.' },
        { label: 'Laad zo nodig oudere meldingen', description: 'Staan er meer meldingen dan direct worden getoond, kies dan Oudere meldingen laden.' },
        { label: 'Open of rond af', description: 'Klik op een melding om de bijbehorende pagina te openen, of kies Alles gelezen om alle openstaande meldingen af te ronden.' },
      ],
      result: 'Ongelezen meldingen blijven server-side bij jouw account staan. Ook meldingen die binnenkomen terwijl je niet in de webapp bent, verschijnen na je volgende aanmelding.',
      warning: 'De bel beweegt niet opnieuw voor meldingen die bij het aanmelden al ongelezen waren. Daardoor is meteen duidelijk welke melding tijdens je actieve sessie nieuw binnenkomt.',
    },
  ],
  'account-access': [
    {
      id: 'account-finish-invitation',
      title: 'Een uitnodiging afronden',
      intro: 'Maak je account gebruiksklaar via de persoonlijke uitnodigingslink.',
      prerequisites: ['Gebruik de nieuwste uitnodigingsmail.', 'Een uitnodigingslink is 60 minuten geldig.'],
      steps: [
        { label: 'Open de uitnodigingslink', description: 'Klik in de ontvangen e-mail op de registratielink. Deel deze link niet met iemand anders.' },
        { label: 'Maak je wachtwoord', description: 'Vul Wachtwoord en Wachtwoord bevestigen in en kies Account activeren.' },
        { label: 'Rond MFA af wanneer dit verschijnt', description: 'Scan de QR-code met je beveiligingsapp, vul de actuele zescijferige MFA-code in en kies MFA activeren.' },
        { label: 'Kies Android of iOS', description: 'Open vanuit de wizard de juiste app-link, installeer de operator-app en open daarin de QR-scanner.' },
        { label: 'Koppel de app', description: 'Maak in de wizard een persoonlijke koppel-QR en scan deze direct met de operator-app. De QR is eenmalig en 30 seconden geldig.' },
        { label: 'Rond de wizard af', description: 'Doorloop alleen de stappen voor apps waartoe je toegang hebt en kies uiteindelijk Naar D.I.S.' },
        { label: 'Vul ontbrekende profielgegevens aan', description: 'Verschijnt Vul je gegevens aan, vul dan voornaam, achternaam, internationaal telefoonnummer, land en woonplaats in. Voor Nederland en België is ook provincie of regio nodig.' },
      ],
      result: 'Je account wordt actief en de gekozen mobiele app is met de persoonlijke QR-code veilig gekoppeld.',
      warning: 'Is de link verlopen, vraag dan een beheerder om de uitnodiging opnieuw te versturen.',
    },
    {
      id: 'account-sign-in-help',
      title: 'Aanmelden en problemen oplossen',
      intro: 'Volg deze volgorde wanneer aanmelden niet meteen lukt.',
      steps: [
        { label: 'Vul e-mailadres en wachtwoord in', description: 'Gebruik het e-mailadres waarop je bent uitgenodigd en kies Inloggen.' },
        { label: 'Vul zo nodig de beveiligingscode in', description: 'Open je beveiligingsapp en gebruik de actuele code. Een oude code werkt niet.' },
        { label: 'Wacht bij een tijdelijke blokkade', description: 'Na vijf verkeerde wachtwoorden wacht je vijf minuten. Na vijf verkeerde beveiligingscodes begin je opnieuw bij het aanmeldscherm.' },
        { label: 'Controleer onderhoud', description: 'Zie je het onderhoudsscherm, wacht dan. De pagina controleert ongeveer elke twintig seconden vanzelf opnieuw.' },
        { label: 'Vraag hulp bij een accountblokkade', description: 'Bij Geschorst of Geblokkeerd moet een beheerder je account controleren.' },
      ],
      result: 'Na een geldige aanmelding opent DIS het eerste onderdeel waarvoor je toegang hebt.',
      warning: 'Blijf niet snel achter elkaar codes proberen. Daarmee verleng je het probleem en kan het account opnieuw tijdelijk worden geblokkeerd.',
    },
  ],
  profile: [
    {
      id: 'profile-update-details',
      title: 'Persoonsgegevens aanpassen',
      intro: 'Werk je naam, telefoonnummer of woonplaats zelf bij.',
      steps: [
        { label: 'Open Profiel', description: 'Klik rechtsboven op je naam en kies Profiel.' },
        { label: 'Wijzig de velden', description: 'Pas voornaam, achternaam, telefoonnummer, land, woonplaats en provincie of regio aan. Het e-mailadres is hier alleen zichtbaar.' },
        { label: 'Controleer het telefoonnummer', description: 'Gebruik een internationaal nummer, bijvoorbeeld +31 of +32.' },
        { label: 'Sla de gegevens op', description: 'Kies Gegevens opslaan en wacht op de bevestiging.' },
      ],
      result: 'De nieuwe profielgegevens worden gebruikt in de webapp, het adresboek en bij globale woonplaatsweergave.',
    },
    {
      id: 'profile-plan-availability',
      title: 'Beschikbaarheid per dagdeel plannen',
      intro: 'Stel je vaste week in en maak afwijkingen voor de komende twee weken.',
      steps: [
        { label: 'Open Mijn beschikbaarheid', description: 'Ga op Profiel naar het blok Mijn beschikbaarheid en kies Dagdelen plannen.' },
        { label: 'Stel vaste weekdagen in', description: 'Klik per weekdag op Ochtend, Middag of Avond. Aan betekent standaard beschikbaar; Uit betekent standaard niet beschikbaar.' },
        { label: 'Sla het vaste patroon op', description: 'Kies Vaste dagdelen opslaan. Dit patroon geldt voor toekomstige weken.' },
        { label: 'Plan een afwijkende datum', description: 'Ga in hetzelfde venster naar 2 weken vooruit plannen en klik bij de gewenste datum op het dagdeel.' },
        { label: 'Controleer de nieuwe stand', description: 'Een afwijkende datum wordt direct opgeslagen en gaat voor het vaste weekpatroon.' },
      ],
      result: 'DIS gebruikt per dagdeel eerst een datumafwijking en anders je vaste weekpatroon.',
      warning: 'De knoppen bij de komende twee weken slaan direct op. Alleen het vaste weekpatroon heeft de aparte knop Vaste dagdelen opslaan. Een datumafwijking kan nu niet worden gewist om weer automatisch op het vaste patroon terug te vallen.',
    },
    {
      id: 'profile-manage-own-resources',
      title: 'Een eigen middel of certificaat bijhouden',
      intro: 'Houd operationele gegevens actueel wanneer je hiervoor invoervelden op Profiel ziet.',
      steps: [
        { label: 'Kies het juiste blok', description: 'Ga naar Mijn assets voor een middel of Mijn certificaten voor een bevoegdheid.' },
        { label: 'Open het invoervenster', description: 'Kies Asset toevoegen of Certificaat toevoegen. Het formulier opent in een apart venster.' },
        { label: 'Vul de gevraagde gegevens in', description: 'Kies bij een drone ook het dronetype. Vul bij een certificaat minimaal soort en afgiftedatum in.' },
        { label: 'Sla de invoer op', description: 'Gebruik de primaire opslagknop onder in het venster.' },
        { label: 'Pas een bestaand item aan', description: 'Kies het potlood in de compacte rij. Wijzig de gegevens in het venster en sla opnieuw op.' },
        { label: 'Verwijder alleen bewust', description: 'Open eerst Aanpassen en kies daar Verwijderen. Controleer de naam en gevolgen in de extra bevestiging voordat je definitief verwijdert.' },
      ],
      result: 'Het middel of certificaat staat bij je profiel en kan worden gebruikt voor inzetcontrole.',
      warning: 'Verwijder alleen een registratie die echt niet meer bij jou hoort. Een verlopen certificaat laat je bij voorkeur staan met de juiste verloopdatum.',
    },
  ],
  'mobile-app': [
    {
      id: 'mobile-pair-qr',
      title: 'De Operator-app koppelen met QR-code',
      intro: 'Koppel de Operator-app zonder gebruikersnaam en wachtwoord.',
      mobileApp: 'operator',
      prerequisites: ['Installeer de Operator-app.', 'Sta cameragebruik toe wanneer de app daarom vraagt.'],
      steps: [
        { label: 'Open Mijn toestellen', description: 'Ga in de webapp naar Profiel en kies bij Mijn toestellen de knop Toestel toevoegen.' },
        { label: 'Open de Operator-app', description: 'Gebruik de scanfunctie in de Operator-app op Android of iPhone.' },
        { label: 'Open de scanner', description: 'Open in de mobiele app de functie om een QR-koppelcode te scannen.' },
        { label: 'Scan de zichtbare code', description: 'Richt de camera op de QR-code in de webapp. Iedere code is 30 seconden geldig en het webvenster maakt automatisch een nieuwe.' },
        { label: 'Geef het toestel een naam', description: 'Vul in de mobiele app een herkenbare naam in, bijvoorbeeld Prive telefoon of Meldkamertablet.' },
        { label: 'Controleer Mijn toestellen', description: 'Na koppelen verschijnt het toestel in de lijst op je profiel.' },
      ],
      result: 'De app blijft onder jouw account aangemeld. Nadat de app het toestel en push heeft geregistreerd, verschijnt het bij Mijn toestellen.',
      warning: 'Scan altijd de code die op dat moment zichtbaar is. Een verlopen code wordt geweigerd.',
    },
    {
      id: 'mobile-pair-same-device',
      title: 'Koppelen op dezelfde telefoon',
      intro: 'Gebruik de knop of de handmatige gegevens wanneer je de QR-code niet kunt scannen.',
      mobileApp: 'operator',
      steps: [
        { label: 'Open Toestel toevoegen', description: 'Open Profiel in de browser op je telefoon en kies Toestel toevoegen.' },
        { label: 'Kies Open app en koppel dit toestel', description: 'De mobiele app wordt geopend met server en koppelcode.' },
        { label: 'Gebruik zo nodig Handmatig koppelen', description: 'Werkt de knop niet, neem dan in de mobiele app de Server en Koppelcode over uit het webvenster.' },
        { label: 'Rond de toestelgegevens af', description: 'Controleer het toesteltype en geef het toestel een herkenbare naam.' },
      ],
      result: 'Het toestel verschijnt bij Mijn toestellen zonder dat een tweede scherm nodig is.',
    },
    {
      id: 'mobile-remove-device',
      title: 'Een gekoppeld toestel verwijderen',
      intro: 'Trek toegang in wanneer een toestel weg, vervangen of niet meer vertrouwd is.',
      steps: [
        { label: 'Open Mijn toestellen', description: 'Ga naar Profiel en zoek het juiste toestel op naam, type en laatste contact.' },
        { label: 'Kies Verwijderen', description: 'DIS opent het venster Toestel verwijderen?.' },
        { label: 'Controleer de toestelnaam', description: 'Zorg dat je niet per ongeluk je huidige of een operationeel gebruikt toestel verwijdert.' },
        { label: 'Bevestig verwijderen', description: 'Kies de rode verwijderknop in het bevestigingsvenster.' },
      ],
      result: 'De mobiele sessie en toestelregistratie worden direct ingetrokken. De verwijderde app moet opnieuw worden gekoppeld.',
      warning: 'Wanneer geen actief app-toestel overblijft, kan DIS push uitschakelen en je op niet beschikbaar zetten.',
    },
  ],
  calendar: [
    {
      id: 'calendar-view-events',
      title: 'Een agenda-item bekijken',
      intro: 'Bekijk trainingen, open dagen en teammomenten.',
      permissions: ['calendar.view'],
      steps: [
        { label: 'Open Agenda', description: 'Kies Agenda in het menu.' },
        { label: 'Ga naar Geplande items', description: 'De kaarten tonen datum, type, titel, locatie, agendagroepen en eventuele inschrijfstatus.' },
        { label: 'Controleer de groepen', description: 'Een item kan voor meerdere agendagroepen bedoeld zijn. De systeemgroep Iedereen bevat automatisch alle gebruikers.' },
      ],
      result: 'Je weet wanneer en waar het moment plaatsvindt. De mobiele app toont dezelfde agenda en inschrijfstatus.',
    },
    {
      id: 'calendar-register',
      title: 'Jezelf inschrijven of afmelden',
      intro: 'Geef via de webapp of Operator-app aan dat je komt.',
      permissions: ['calendar.view', 'calendar.register'],
      steps: [
        { label: 'Open Agenda', description: 'Zoek het juiste agenda-item in de webapp of Operator-app.' },
        { label: 'Controleer de capaciteit', description: 'Bekijk hoeveel deelnemers zijn ingeschreven en hoeveel plaatsen nog beschikbaar zijn.' },
        { label: 'Kies Ik kom', description: 'De server controleert opnieuw of de inschrijving open is en of er nog plaats is.' },
        { label: 'Meld je zo nodig af', description: 'Kies Afmelden wanneer je niet meer komt; jouw plaats komt direct vrij.' },
      ],
      result: 'De actuele deelnemersstand en jouw eigen inschrijfstatus worden bijgewerkt.',
      warning: 'Bij de laatste vrije plaats kan iemand anders net eerder zijn. DIS voorkomt dat het maximum wordt overschreden.',
    },
    {
      id: 'calendar-add-event',
      title: 'Een agenda-item toevoegen',
      intro: 'Plan een training, open dag of ander gezamenlijk moment.',
      permissions: ['calendar.view', 'calendar.manage'],
      steps: [
        { label: 'Open Agenda-item toevoegen', description: 'Op de pagina Agenda staat voor beheerders het formulier Agenda-item toevoegen.' },
        { label: 'Vul titel en start in', description: 'Titel en Start zijn verplicht. Kies daarnaast Type en zo nodig Einde en Locatie.' },
        { label: 'Kies de doelgroep', description: 'Kies Iedereen of selecteer één of meer specifieke groepen. Zodra een specifieke groep is geselecteerd, wordt Iedereen automatisch uitgezet.' },
        { label: 'Stel inschrijving in', description: 'Schakel inschrijving in en vul desgewenst een maximumaantal deelnemers in. Leeg betekent onbeperkt.' },
        { label: 'Voeg uitleg toe', description: 'Gebruik Omschrijving voor informatie die deelnemers vooraf nodig hebben.' },
        { label: 'Kies Toevoegen', description: 'Wacht op de melding dat het agenda-item is opgeslagen.' },
      ],
      result: 'Het item verschijnt bij Geplande items en wordt zichtbaar in webapp en mobiele agenda.',
    },
    {
      id: 'calendar-edit-event',
      title: 'Een agenda-item aanpassen',
      intro: 'Werk de planning of inhoud van een bestaand moment bij.',
      permissions: ['calendar.view', 'calendar.manage'],
      steps: [
        { label: 'Zoek het item', description: 'Ga in Agenda naar de kaart van het juiste item.' },
        { label: 'Kies Aanpassen', description: 'Gebruik de knop onderaan de kaart.' },
        { label: 'Werk de gegevens bij', description: 'Controleer titel, tijd, locatie, groepen, inschrijving, capaciteit en omschrijving.' },
        { label: 'Sla de wijzigingen op', description: 'Kies Wijzigingen opslaan en wacht op de bevestiging.' },
      ],
      result: 'Het bijgewerkte agenda-item is direct zichtbaar in de webapp en mobiele agenda.',
    },
    {
      id: 'calendar-delete-event',
      title: 'Een agenda-item verwijderen',
      intro: 'Haal een moment weg dat niet meer doorgaat.',
      permissions: ['calendar.view', 'calendar.manage'],
      steps: [
        { label: 'Zoek het item', description: 'Ga in Agenda naar de kaart van het juiste item.' },
        { label: 'Controleer datum en titel', description: 'Controleer goed dat je het juiste item hebt.' },
        { label: 'Kies Verwijderen', description: 'Gebruik de knop onderaan de kaart.' },
      ],
      result: 'Het agenda-item verdwijnt direct uit de webapp en mobiele agenda.',
      warning: 'Verwijderen kan niet worden hersteld. Controleer daarom eerst of je het juiste item hebt gekozen.',
    },
    {
      id: 'calendar-manage-participants',
      title: 'Deelnemers beheren',
      intro: 'Schrijf namens de organisatie een gebruiker in of uit.',
      permissions: ['calendar.view', 'calendar.registrations.view', 'calendar.registrations.manage'],
      steps: [
        { label: 'Open Deelnemers', description: 'Kies Deelnemers bij het betreffende agenda-item.' },
        { label: 'Zoek een gebruiker', description: 'Alleen actieve gebruikers binnen de effectieve doelgroep zijn inschrijfbaar.' },
        { label: 'Schrijf in of uit', description: 'Gebruik Inschrijven of Uitschrijven bij de juiste gebruiker.' },
      ],
      result: 'De deelnemerslijst en capaciteit worden server-side bijgewerkt en de beheeractie wordt geaudit.',
    },
    {
      id: 'calendar-manage-groups',
      title: 'Agendagroepen beheren',
      intro: 'Combineer directe gebruikers en via teams overgeërfde leden in herbruikbare groepen.',
      permissions: ['calendar.view', 'calendar.groups.manage'],
      steps: [
        { label: 'Open Agendagroepen', description: 'Gebruik de knop bovenaan de pagina Agenda.' },
        { label: 'Voeg leden toe', description: 'Selecteer individuele gebruikers en één of meer teams. Teamlidmaatschap werkt automatisch door.' },
        { label: 'Sla de groep op', description: 'De groep kan daarna bij één of meer agenda-items worden geselecteerd.' },
      ],
      result: 'De effectieve doelgroep is de unieke combinatie van directe gebruikers en actuele teamleden.',
      warning: 'De systeemgroep Iedereen bevat automatisch alle gebruikers en kan niet worden gewijzigd of verwijderd.',
    },
  ],
  'product-requests': [
    {
      id: 'product-request-submit',
      title: 'Een bug, aanpassing of feature indienen',
      intro: 'Leg één concreet verzoek vast zodat het beoordeeld en opgevolgd kan worden.',
      permissions: ['product-requests.view', 'product-requests.create'],
      steps: [
        { label: 'Open Verzoeken', description: 'Kies Verzoeken in het menu onder Account.' },
        { label: 'Kies Nieuw verzoek', description: 'Selecteer Bug, Aanpassing of Feature als type.' },
        { label: 'Schrijf een herkenbare titel', description: 'Vat de vraag kort samen zonder persoonsgegevens of operationele geheime informatie.' },
        { label: 'Beschrijf de gewenste uitkomst', description: 'Leg uit wat er misgaat of wat er moet veranderen en wanneer dat merkbaar is.' },
        { label: 'Kies Verzoek indienen', description: 'Het verzoek verschijnt direct in Alle en Mijn verzoeken.' },
      ],
      result: 'Het verzoek is geregistreerd met status Open en kan door een behandelaar worden opgepakt.',
    },
    {
      id: 'product-request-update-own',
      title: 'Je eigen open verzoek aanpassen',
      intro: 'Vul een eigen verzoek aan zolang het nog wijzigbaar is.',
      permissions: ['product-requests.view', 'product-requests.update-own'],
      steps: [
        { label: 'Open Mijn verzoeken', description: 'Zoek het verzoek en open de detailweergave.' },
        { label: 'Kies Aanpassen', description: 'De knop staat alleen wanneer de server dit verzoek nog wijzigbaar vindt.' },
        { label: 'Werk type, titel of omschrijving bij', description: 'Bewaar de oorspronkelijke bedoeling en maak ontbrekende informatie concreet.' },
        { label: 'Kies Wijzigingen opslaan', description: 'Bij een gelijktijdige wijziging laadt DIS eerst de nieuwste versie.' },
      ],
      result: 'De nieuwste inhoud en het wijzigingstijdstip zijn zichtbaar voor alle lezers.',
    },
    {
      id: 'product-request-update-any',
      title: 'De inhoud van een verzoek aanpassen',
      intro: 'Corrigeer of verduidelijk een niet-afgesloten verzoek zonder de oorspronkelijke aanvrager te wijzigen.',
      permissions: ['product-requests.view', 'product-requests.update-any'],
      steps: [
        { label: 'Open het verzoek', description: 'Zoek het verzoek in Te behandelen of Alle verzoeken en open de detailweergave.' },
        { label: 'Controleer de aanvrager', description: 'De aanvrager staat ter informatie bovenaan en kan niet worden gewijzigd.' },
        { label: 'Kies Aanpassen', description: 'Wijzig alleen het type, de titel of de omschrijving.' },
        { label: 'Kies Wijzigingen opslaan', description: 'DIS controleert de actuele versie en registreert wie de inhoud heeft aangepast.' },
      ],
      result: 'Type, titel en omschrijving zijn bijgewerkt; de aanvrager en status zijn ongewijzigd gebleven.',
    },
    {
      id: 'product-request-resolve',
      title: 'Een verzoek behandelen',
      intro: 'Leg iedere statuswijziging uit zodat de afhandeling controleerbaar blijft.',
      permissions: ['product-requests.view', 'product-requests.resolve'],
      steps: [
        { label: 'Open Te behandelen', description: 'Bekijk openstaande en lopende verzoeken.' },
        { label: 'Open het juiste verzoek', description: 'Controleer type, indiener, omschrijving en huidige status.' },
        { label: 'Kies de nieuwe status', description: 'Zet het verzoek in behandeling, opgelost, afgewezen of heropen het.' },
        { label: 'Vul de toelichting in', description: 'Beschrijf wat er is besloten of uitgevoerd. Deze toelichting is verplicht.' },
        { label: 'Kies Afhandeling opslaan', description: 'DIS controleert de actuele versie voordat de wijziging wordt toegepast.' },
      ],
      result: 'De status en toelichting zijn bijgewerkt zonder de oorspronkelijke melding te overschrijven.',
    },
  ],
} satisfies ManualGuideMap;
