import type { ManualGuideMap } from '../manualTypes';

export const managementManualGuides = {
  'manual-push': [
    {
      id: 'manual-push-send',
      title: 'Een losse pushmelding versturen',
      intro: 'Stuur een algemene mededeling die niet bij een incident hoort.',
      prerequisites: ['Gebruik voor een echte inzet altijd de alarmering op het incident.', 'Bepaal vooraf welke teams, rollen of personen het bericht nodig hebben.'],
      steps: [
        { label: 'Open Handmatige pushmelding', description: 'Kies Pushmeldingen in het menu onder Beheer.' },
        { label: 'Vul Titel en Bericht in', description: 'Schrijf kort en duidelijk wat de ontvanger moet weten. De titel mag maximaal 120 tekens en het bericht maximaal 1.200 tekens bevatten.' },
        { label: 'Selecteer ontvangers', description: 'Vink één of meer Teams, Rollen of Individuele gebruikers aan.' },
        { label: 'Controleer ontvangerselecties', description: 'De teller telt je aangevinkte groepen en personen. Het is niet het definitieve aantal bereikbare gebruikers.' },
        { label: 'Kies Pushmelding versturen', description: 'Wacht op de terugmelding met hoeveel gebruikers en toestellen zijn klaargezet.' },
      ],
      result: 'DIS voegt dubbele selecties samen en zet het bericht klaar voor actieve, bereikbare operator-toestellen.',
      warning: 'Klaargezet is geen afleverbevestiging. Een offline gebruiker, uitgeschakelde push of ongeldig toestel kan ervoor zorgen dat het bericht niet aankomt.',
    },
    {
      id: 'manual-push-check-delivery',
      title: 'Controleren waarom een pushmelding niet aankwam',
      intro: 'Gebruik de laatste afleverpogingen voor een eerste technische controle.',
      steps: [
        { label: 'Ga naar Laatste afleverpogingen', description: 'Dit overzicht staat onder het verzendformulier.' },
        { label: 'Controleer Tijd en Type', description: 'Zoek de poging die bij het verzendmoment en berichttype hoort.' },
        { label: 'Lees Status en Fout', description: 'Een foutcode geeft aan dat de afleverpoging niet normaal is verwerkt.' },
        { label: 'Controleer daarna het toestel', description: 'Bekijk zo nodig bij de gebruiker of een actief operator-toestel, recente heartbeat en pushregistratie aanwezig zijn.' },
      ],
      result: 'Je hebt vastgesteld of DIS de melding heeft klaargezet en of een technische fout is geregistreerd.',
    },
  ],
  forms: [
    {
      id: 'forms-choose-build',
      title: 'Het juiste formulier opbouwen',
      intro: 'Maak het incidentformulier of inzetrapport visueel met losse onderdelen.',
      prerequisites: ['Bepaal eerst welke informatie echt nodig is.', 'Maak grote wijzigingen bij voorkeur buiten een actieve inzet.'],
      steps: [
        { label: 'Open Formulieren', description: 'Kies de tab Inzetrapport of Incidentformulier.' },
        { label: 'Bekijk het formulier in het canvas', description: 'Het midden van de pagina laat de huidige volgorde en breedte van blokken zien.' },
        { label: 'Voeg een veld of sectie toe', description: 'Klik op een onderdeel of sleep het naar de gewenste plaats in het canvas.' },
        { label: 'Verplaats het onderdeel', description: 'Sleep het blok aan de greep. Wanneer je bij de boven- of onderrand komt, schuift de pagina automatisch mee.' },
        { label: 'Stel het onderdeel rechts in', description: 'Kies label, type, breedte, zichtbaarheid, verplichting en eventuele keuzes.' },
        { label: 'Kies Formulier opslaan', description: 'Pas na deze knop wordt de nieuwe opbouw actief.' },
      ],
      result: 'Nieuwe formulieren gebruiken de opgeslagen opbouw. De editor is een benadering; de mobiele app zet dezelfde velden in een mobiele indeling.',
      warning: 'Er is geen automatisch opslaan en geen knop om een oude versie terug te zetten. Een gewijzigde veldnaam is pas definitief na Formulier opslaan.',
    },
    {
      id: 'forms-configure-field',
      title: 'Een invoerveld of keuzeveld instellen',
      intro: 'Kies een veldtype dat past bij de informatie die iemand moet invullen.',
      steps: [
        { label: 'Selecteer het veld in het canvas', description: 'De eigenschappen van dat veld verschijnen rechts.' },
        { label: 'Geef een duidelijk label', description: 'Schrijf wat de invuller moet opgeven, niet alleen een interne afkorting.' },
        { label: 'Kies het veldtype', description: 'Gebruik tekst, groot tekstvak, getal, telefoonnummer, vluchttijd, dropdown, radio, checkbox of sectie.' },
        { label: 'Stel Verplicht en Zichtbaar in', description: 'Maak alleen essentiële informatie verplicht en verberg velden die niet meer gebruikt moeten worden.' },
        { label: 'Kies de breedte', description: 'Gebruik halve breedte om twee korte velden naast elkaar te zetten en volledige breedte voor langere invoer.' },
        { label: 'Voeg keuzes per regel toe', description: 'Bij dropdown en radio staat iedere antwoordmogelijkheid op een nieuwe regel. Gebruik minimaal twee opties.' },
      ],
      result: 'Het veld gedraagt zich bij invoer volgens het gekozen type en de ingestelde regels.',
      warning: 'Voor een telefoonveld is een internationaal Nederlands of Belgisch nummer nodig. Het type Vluchttijd gebruikt een begin- en eindtijd.',
    },
    {
      id: 'forms-incident-layout',
      title: 'Het incidentformulier indelen',
      intro: 'Combineer vaste operationele modules met eigen invoervelden.',
      steps: [
        { label: 'Kies Incidentformulier', description: 'Het canvas toont de webindeling voor incident aanmaken en aanpassen.' },
        { label: 'Plaats de vaste modules', description: 'Verplaats onder meer incidentgegevens, melder, locatie en teams naar een logische volgorde.' },
        { label: 'Laat vergrendelde onderdelen staan', description: 'Titel, details en de vaste modules die nodig zijn voor locatie, melder en alarmering kunnen niet veilig worden verwijderd.' },
        { label: 'Voeg eigen blokken en velden toe', description: 'Gebruik secties om bij elkaar horende informatie duidelijk te groeperen.' },
        { label: 'Maak pushvelden beschikbaar', description: 'Zet bij een geschikt incidentveld aan dat het als variabele in incident-pushsjablonen mag worden gebruikt.' },
        { label: 'Sla op en test een concept', description: 'Open na opslaan een nieuw conceptincident en controleer de volledige invoer zonder te alarmeren.' },
      ],
      result: 'De webapp gebruikt de nieuwe incidentindeling en Branding kan toegestane incidentvelden als pushvariabele aanbieden.',
      warning: 'Een bestaand incident bewaart zijn eigen veldwaarden. Verwijder een veelgebruikt veld alleen wanneer oude dossiers leesbaar blijven.',
    },
    {
      id: 'forms-pilot-report',
      title: 'Het inzetrapport voor web en operator-app instellen',
      intro: 'Bepaal welke informatie na een inzet door de piloot wordt vastgelegd.',
      steps: [
        { label: 'Kies Inzetrapport', description: 'Dit formulier wordt gebruikt op Rapporten en in de operator-app.' },
        { label: 'Maak secties en velden', description: 'Zet de vragen in de volgorde waarin de piloot ze na de inzet kan beantwoorden.' },
        { label: 'Kies per veld de appbeschikbaarheid', description: 'Zet alleen velden aan die in de operator-app ingevuld mogen worden.' },
        { label: 'Controleer verplichte velden', description: 'Laat minimaal één zichtbaar invoerveld over en maak alleen noodzakelijke invoer verplicht.' },
        { label: 'Kies Formulier opslaan', description: 'Test daarna zowel invullen namens een gebruiker in de webapp als invullen in de operator-app.' },
      ],
      result: 'Web en operator-app gebruiken dezelfde beschikbare velddefinities in een indeling die bij hun scherm past.',
      warning: 'Velden uit het inzetrapport zijn niet beschikbaar als variabele in incident-pushmeldingen.',
    },
  ],
  branding: [
    {
      id: 'branding-general-logo',
      title: 'Naam, inlogteksten en logo aanpassen',
      intro: 'Werk de zichtbare identiteit van DIS centraal bij.',
      steps: [
        { label: 'Open Branding en kies Algemeen', description: 'Wijzig Applicatienaam, Korte naam, Organisatienaam, Authenticator naam, inlogteksten en Mail afzendernaam.' },
        { label: 'Kies Branding opslaan', description: 'Controleer de bevestiging voordat je naar een andere pagina gaat.' },
        { label: 'Open de tab Logo', description: 'Bekijk eerst het huidige voorbeeld.' },
        { label: 'Kies Logo uploaden', description: 'Selecteer een PNG-, JPEG- of WebP-bestand. De upload wordt direct opgeslagen.' },
        { label: 'Controleer de header en login', description: 'Herlaad zo nodig de pagina om de uiteindelijke combinatie van naam en logo te zien.' },
      ],
      result: 'De nieuwe naam en het logo worden gebruikt op de webapp en waar de mobiele configuratie deze branding overneemt.',
      warning: 'Logo uploaden en Logo verwijderen slaan direct op. Andere brandingvelden pas na Branding opslaan.',
    },
    {
      id: 'branding-push-template',
      title: 'Een incident-pushsjabloon aanpassen',
      intro: 'Bepaal per soort melding welke tekst een operator ontvangt.',
      steps: [
        { label: 'Open de tab Push templates', description: 'Kies Vooraankondiging, Alarmering, urgente opschaling, Nadere info of Annulering.' },
        { label: 'Wijzig titel en tekst', description: 'Houd het belangrijkste deel vooraan zodat het ook op een klein meldingsscherm duidelijk is.' },
        { label: 'Voeg een beschikbare variabele toe', description: 'Gebruik de variabeleknoppen van precies dit sjabloon. DIS plaatst de code op de cursorpositie.' },
        { label: 'Controleer spaties en leestekens', description: 'Zet vaste tekst en variabelen zo dat het bericht ook goed leest wanneer een waarde ontbreekt.' },
        { label: 'Kies Branding opslaan', description: 'Test daarna met een concept of proefomgeving voordat je een echte inzet alarmeert.' },
      ],
      result: 'Nieuwe incidentmeldingen worden met het opgeslagen sjabloon opgebouwd.',
      warning: 'Deze sjablonen gelden niet voor Handmatige pushmelding. Gebruik alleen variabelen die bij het gekozen sjabloon worden getoond.',
    },
    {
      id: 'branding-mail-template',
      title: 'Uitnodigings- en verloopmails aanpassen',
      intro: 'Houd e-mailteksten herkenbaar en laat noodzakelijke links en gegevens staan.',
      steps: [
        { label: 'Kies de juiste tab', description: 'Gebruik Mail templates voor Uitnodiging en Verloopmail templates voor certificaten of middelen.' },
        { label: 'Wijzig Onderwerp en Tekst', description: 'Schrijf in eenvoudige taal wat de ontvanger moet doen.' },
        { label: 'Controleer beschikbare tokens', description: 'Laat noodzakelijke tokens, zoals de registratielink of verloopdatum, in het juiste sjabloon staan.' },
        { label: 'Kies Branding opslaan', description: 'Controleer de bevestiging en verstuur zo nodig een nieuwe uitnodiging naar een testgebruiker.' },
      ],
      result: 'Nieuwe uitnodigings- en verloopmails gebruiken de bijgewerkte tekst.',
    },
    {
      id: 'branding-expiry-warning',
      title: 'Verloopwaarschuwingen instellen',
      intro: 'Bepaal hoeveel dagen vóór verloop een e-mail wordt verstuurd.',
      steps: [
        { label: 'Open Verloopmails', description: 'Bekijk de instellingen voor certificaten en middelen.' },
        { label: 'Vul het aantal dagen vooraf in', description: 'Kies een termijn waarmee verlenging of onderhoud nog haalbaar is.' },
        { label: 'Controleer de ontvanger en tekst', description: 'Ga zo nodig terug naar Verloopmail templates om de inhoud aan te passen.' },
        { label: 'Kies Branding opslaan', description: 'De nieuwe termijn geldt voor toekomstige controles.' },
      ],
      result: 'DIS kan vooraf en op de verloopdatum de ingestelde waarschuwing versturen.',
    },
  ],
  admin: [
    {
      id: 'admin-save-test-mail-push',
      title: 'Push- en mailinstellingen wijzigen en testen',
      intro: 'Sla verbindinggegevens eerst op en voer daarna pas een test uit.',
      permissions: ['settings.manage'],
      steps: [
        { label: 'Open Instellingen', description: 'Ga naar het onderdeel met push-, mobiele en mailconfiguratie.' },
        { label: 'Wijzig alleen de benodigde velden', description: 'Controleer servernamen, afzender en publieke mobiele configuratie zorgvuldig.' },
        { label: 'Kies de bijbehorende opslagknop', description: 'Sla het betreffende instellingenblok op voordat je test.' },
        { label: 'Voer de test uit', description: 'Gebruik de testmail of pushcontrole en lees de volledige terugmelding.' },
        { label: 'Controleer ontvangst', description: 'Een geslaagde technische test is pas compleet wanneer het bericht ook bij de verwachte ontvanger aankomt.' },
      ],
      result: 'De opgeslagen configuratie wordt voor nieuwe mail- en pushacties gebruikt.',
      warning: 'De testmail gebruikt de opgeslagen instellingen en gaat naar het e-mailadres van de ingelogde beheerder.',
    },
    {
      id: 'admin-security-heartbeat',
      title: 'Heartbeat, MFA en wachtwoordeisen instellen',
      intro: 'Beheer organisatiebrede beveiliging en de grens voor online toestellen.',
      permissions: ['settings.manage'],
      steps: [
        { label: 'Open het juiste instellingenblok', description: 'Zoek Heartbeat en daarna MFA en wachtwoordeisen.' },
        { label: 'Kies het heartbeat-interval', description: 'Dit bepaalt hoe vaak operator-toestellen zich horen te melden. Offline volgt na de ingestelde gemiste periode.' },
        { label: 'Kies de algemene MFA-regel', description: 'Zet MFA voor alle gebruikers aan wanneer dit organisatiebeleid is. Rollen met admin-app-toegang gebruiken altijd MFA.' },
        { label: 'Stel de wachtwoordeisen in', description: 'Kies een minimumlengte en de vereiste tekenklassen volgens het beveiligingsbeleid.' },
        { label: 'Sla ieder blok op', description: 'Controleer de bevestiging en informeer gebruikers over aangescherpte eisen.' },
      ],
      result: 'Nieuwe controles gebruiken de opgeslagen heartbeat- en beveiligingsinstellingen.',
      warning: 'Een te ruim heartbeat-interval laat offline toestellen langer online lijken. Een te krap interval kan bij energiebesparing onterecht offline tonen.',
    },
    {
      id: 'admin-map-log-visibility',
      title: 'Meldkamers en zichtbare incidentlog instellen',
      intro: 'Beheer vaste kaartpunten en bepaal welke logsoorten mobiele gebruikers mogen lezen.',
      permissions: ['settings.manage'],
      steps: [
        { label: 'Open de kaartinstellingen', description: 'Voeg een meldkamer toe door het adres te zoeken en de juiste suggestie te kiezen.' },
        { label: 'Controleer naam en kaartpunt', description: 'Zorg dat de meldkamer op de bedoelde locatie staat voordat je opslaat.' },
        { label: 'Kies de bewaartermijn voor locaties', description: 'Gebruik alleen de termijn die operationeel en privacytechnisch nodig is.' },
        { label: 'Open de incidentloginstellingen', description: 'Vink alleen logtypen aan die een mobiele operator voor de inzet moet zien.' },
        { label: 'Sla de instellingen op', description: 'Verwijderde meldkamers en gewijzigde zichtbaarheid worden pas na opslaan actief.' },
      ],
      result: 'De operationele kaart en mobiele incidentlog gebruiken de nieuwe instellingen.',
      warning: 'Meldkamerkladblokregels blijven intern. Maak geen gevoelige beheer- of auditregels zichtbaar voor mobiele gebruikers.',
    },
    {
      id: 'admin-store-review',
      title: 'Revieweraccounts voor appstorecontrole beheren',
      intro: 'Geef Apple of Google beperkte, platformgebonden toegang zonder een echte operationele gebruiker te gebruiken.',
      permissions: ['settings.manage'],
      steps: [
        { label: 'Open de tab Store', description: 'Kies het afzonderlijke Apple- of Google-revieweraccount.' },
        { label: 'Stel een sterk wachtwoord in', description: 'Gebruik minimaal twaalf tekens en deel het alleen via het beveiligde reviewkanaal.' },
        { label: 'Activeer het account', description: 'Apple kan uitsluitend in de iOS-operatorapp inloggen; Google uitsluitend in de Android-operatorapp.' },
        { label: 'Controleer het infoblok', description: 'Bekijk het laatste inlogmoment en de geldigheid van de reviewsessie.' },
        { label: 'Schakel uit na de controle', description: 'Uitschakelen trekt alle actieve reviewsessies direct in.' },
      ],
      result: 'De reviewer kan maximaal 24 uur met het beperkte reviewtoken werken zonder operationele gegevens te wijzigen.',
      warning: 'Revieweraccounts kunnen nooit in het webportaal inloggen en zien uitsluitend afgeschermde testdata. MFA is alleen voor deze revieweraccounts uitgeschakeld.',
    },
    {
      id: 'admin-revoke-device',
      title: 'Een mobiel toestel centraal intrekken',
      intro: 'Stop push en mobiele toegang van een verloren of niet meer toegestaan toestel.',
      permissions: ['settings.push.tokens.manage'],
      steps: [
        { label: 'Open Mobiele toestellen', description: 'Zoek op gebruiker, toestelnaam, app en laatste contact.' },
        { label: 'Controleer de registratie', description: 'Vergelijk platform, toesteltype en laatste heartbeat zodat je de juiste regel hebt.' },
        { label: 'Kies Intrekken', description: 'Lees de bevestiging en voer de actie uit.' },
        { label: 'Controleer de gebruiker', description: 'Bekijk of andere actieve operator-toestellen overblijven en of beschikbaarheid nog klopt.' },
      ],
      result: 'De toestelregistratie en gekoppelde mobiele sessie zijn ingetrokken; de app moet opnieuw worden gekoppeld.',
      warning: 'Wanneer dit het laatste actieve operator-toestel is, kan push worden uitgeschakeld en de gebruiker niet beschikbaar worden.',
    },
    {
      id: 'admin-update-restart',
      title: 'Systeemupdate uitvoeren en zo nodig herstarten',
      intro: 'Voer onderhoud alleen op een afgesproken operationeel moment uit.',
      permissions: ['system.health.view', 'system.update.execute'],
      prerequisites: ['Controleer of geen actieve inzet wordt verstoord.', 'Controleer of een recente geldige backup bestaat.'],
      steps: [
        { label: 'Open Instellingen en controleer de versie', description: 'Lees huidige versie, beschikbare update en laatste update-uitvoer.' },
        { label: 'Kies de juiste updateactie', description: 'Gebruik Applicatie bijwerken wanneer alleen DIS moet worden bijgewerkt; een volledige update kan ook systeempakketten meenemen.' },
        { label: 'Start de update één keer', description: 'Er kan maar één update tegelijk lopen. Laat het scherm open en volg de status.' },
        { label: 'Controleer het resultaat', description: 'Lees foutmelding en uitvoer volledig en controleer daarna Systeemstatus.' },
        { label: 'Herstart alleen wanneer gevraagd', description: 'Gebruik Server herstarten alleen wanneer de knop beschikbaar is, een herstart nodig is en geen update meer loopt.' },
      ],
      result: 'DIS draait op de bijgewerkte versie en de systeemcontrole is opnieuw beoordeeld.',
      warning: 'Sluit een mislukte update niet af als “klaar”. Bewaar de uitvoer voor technisch onderzoek en voorkom meerdere gelijktijdige herstelacties.',
    },
    {
      id: 'admin-developer-access',
      title: 'Tijdelijke ontwikkeltoegang uitgeven',
      intro: 'Geef een externe technische partij alleen de minimaal benodigde tijdelijke toegang.',
      permissions: ['system.developer-access.manage'],
      steps: [
        { label: 'Open Developer-toegang', description: 'Controleer bestaande toegang en de ingestelde einddatum.' },
        { label: 'Kies de minimale rechten', description: 'Sta alleen de acties toe die voor het afgesproken onderzoek nodig zijn.' },
        { label: 'Vul einddatum en eventueel IP-adressen in', description: 'Beperk de geldigheid en het netwerkbereik zo veel mogelijk.' },
        { label: 'Maak de sleutel', description: 'Kopieer de nieuwe sleutel direct naar het afgesproken veilige kanaal.' },
        { label: 'Controleer en trek na afloop in', description: 'Een nieuwe sleutel vervangt de vorige. Verwijder toegang zodra het werk klaar is.' },
      ],
      result: 'Er bestaat één tijdelijke ontwikkelsleutel met de gekozen beperkingen.',
      warning: 'De volledige sleutel wordt maar één keer getoond. Zet hem niet in e-mail, chatgeschiedenis, broncode of screenshots.',
    },
  ],
  audit: [
    {
      id: 'audit-search-actions',
      title: 'Een beheer- of incidentactie terugzoeken',
      intro: 'Zoek wie een belangrijke wijziging uitvoerde en wanneer dat gebeurde.',
      permissions: ['audit.view'],
      steps: [
        { label: 'Open Audit', description: 'Ga naar Audit filters.' },
        { label: 'Kies een periode', description: 'Beperk Vanaf en Tot tot het moment waarop de wijziging ongeveer plaatsvond.' },
        { label: 'Vul gebruiker of actie in', description: 'Zoek op een deel van de naam, het e-mailadres of de actienaam.' },
        { label: 'Pas filters toe', description: 'Bekijk daarna Tijd, Actie, Uitvoerder, Doel, IP-adres en Reden.' },
        { label: 'Wis of verfijn filters', description: 'Maak de periode kleiner wanneer te veel resultaten verschijnen.' },
      ],
      result: 'Je hebt de relevante auditregel gevonden binnen maximaal 150 getoonde recente resultaten.',
    },
    {
      id: 'audit-search-status',
      title: 'Een statuswijziging terugzoeken',
      intro: 'Controleer de oude en nieuwe operationele status van een gebruiker.',
      permissions: ['status.audit.view'],
      steps: [
        { label: 'Ga naar Status audit', description: 'Gebruik het tweede filterblok op de Auditpagina.' },
        { label: 'Kies gebruiker en periode', description: 'Beperk de resultaten zo veel mogelijk.' },
        { label: 'Pas filters toe', description: 'Lees oude status, nieuwe status, uitvoerder en reden.' },
      ],
      result: 'De statusovergang en de geregistreerde aanleiding zijn zichtbaar.',
    },
  ],
  backups: [
    {
      id: 'backups-configure',
      title: 'Automatische backups instellen',
      intro: 'Kies opslag, planning, bewaartermijn en rapportontvangers.',
      prerequisites: ['Gebruik een opslaglocatie die voldoende ruimte heeft.', 'Voor Samba zijn server, gebruikersnaam, wachtwoord en bereikbare share nodig.'],
      steps: [
        { label: 'Open Backup doel', description: 'Kies Lokaal of Samba share.' },
        { label: 'Vul bij Samba de verbinding in', description: 'Gebruik Paden ophalen om shares te vinden en kies daarna Pad/share. Dit toont paden maar bewijst nog niet dat schrijven lukt.' },
        { label: 'Zet Automatisch backups maken aan', description: 'Kies Dagelijks of Wekelijks en stel dag en tijd in.' },
        { label: 'Kies Aantal bewaren', description: 'Gebruik een waarde van 1 tot en met 365, of 0 voor onbeperkt.' },
        { label: 'Kies rapportontvangers', description: 'Selecteer apart wie een succesrapport en wie een foutrapport ontvangt.' },
        { label: 'Kies Backup doel opslaan', description: 'Controleer daarna het statusblok met actief doel, planning en bewaaraantal.' },
      ],
      result: 'De scheduler gebruikt de opgeslagen planning voor volgende automatische backups.',
      warning: 'Paden ophalen is geen schrijverscontrole. Maak na instellen altijd een handmatige backup en verifieer die.',
    },
    {
      id: 'backups-create-verify',
      title: 'Een handmatige backup maken en verifiëren',
      intro: 'Controleer de volledige keten voordat je op automatische backups vertrouwt.',
      steps: [
        { label: 'Kies het doel bij Backup beheer', description: 'Selecteer Lokaal of Samba share.' },
        { label: 'Kies Backup maken', description: 'Wacht totdat DIS meldt dat de backup is gemaakt.' },
        { label: 'Zoek de nieuwe regel', description: 'Controleer tijd, doel, database, host, versie, grootte en status.' },
        { label: 'Kies Verifieren', description: 'Lees de uitvoer en controleer dat manifest en checksums geldig zijn.' },
      ],
      result: 'Er is een controleerbare backup waarvan de bestanden en checksums door DIS zijn beoordeeld.',
      warning: 'Een regel in de lijst alleen is niet genoeg. Gebruik Verifieren en bewaak ook de foutrapporten.',
    },
    {
      id: 'backups-restore-existing',
      title: 'Een bestaande backup terugzetten',
      intro: 'Herstel database en bestanden alleen tijdens gepland onderhoud.',
      prerequisites: ['Stop operationeel gebruik.', 'Controleer de gekozen backup met Verifieren.', 'Zorg dat de juiste encryptiesleutel beschikbaar is voor een versleutelde backup.'],
      steps: [
        { label: 'Kies Restore bij de juiste backup', description: 'Controleer backup-ID, datum, doel, versie en status.' },
        { label: 'Lees de waarschuwing', description: 'Alle nieuwere database- en bestandsgegevens kunnen verdwijnen.' },
        { label: 'Typ HERSTEL BACKUP', description: 'De knop blijft uit totdat de tekst exact overeenkomt.' },
        { label: 'Kies Restore uitvoeren', description: 'Laat het venster open en lees de volledige uitvoer.' },
        { label: 'Controleer DIS na herstel', description: 'Controleer login, incidenten, bestanden, systeemstatus en de actuele versie voordat gebruik wordt hervat.' },
      ],
      result: 'Database en storage zijn teruggezet naar het moment van de gekozen backup.',
      warning: 'Een restore is ingrijpend en niet ongedaan te maken zonder een andere backup. Nieuwere incidenten en wijzigingen kunnen verdwijnen.',
    },
    {
      id: 'backups-upload-restore',
      title: 'Een backup-ZIP uploaden en terugzetten',
      intro: 'Gebruik een volledige DIS-backup die niet al in de lijst staat.',
      prerequisites: ['Controleer de herkomst van het ZIP-bestand.', 'Gebruik alleen een complete DIS-backup met manifest en checksums.'],
      steps: [
        { label: 'Ga naar Backup uploaden en terugzetten', description: 'Kies bij Backup ZIP het juiste bestand.' },
        { label: 'Typ HERSTEL BACKUP', description: 'Controleer vóór het typen nogmaals bestandsnaam en datum.' },
        { label: 'Kies Upload restore uitvoeren', description: 'DIS uploadt, verifieert en herstelt het bestand in één handeling.' },
        { label: 'Lees de uitvoer en controleer het systeem', description: 'Hervat gebruik pas na een volledige functionele controle.' },
      ],
      result: 'De geüploade backup is eerst technisch gecontroleerd en daarna teruggezet.',
      warning: 'Deze actie heeft geen tussenstap na de verificatie. Zodra de uploadcontrole slaagt, begint het herstel.',
    },
  ],
  system: [
    {
      id: 'system-read-health',
      title: 'De systeemstatus beoordelen',
      intro: 'Gebruik de zelfcontrole als eerste aanwijzing bij een technisch probleem.',
      steps: [
        { label: 'Open Systeemstatus', description: 'Bekijk algemene status, uptime en het controletijdstip.' },
        { label: 'Controleer de diensten', description: 'Lees Backend, Database, Cache, Opslag, Queue en WebSocket.' },
        { label: 'Controleer Firebase en drivers', description: 'Bekijk of Firebase-project, serviceaccount, queuedriver en broadcastdriver zijn ingesteld.' },
        { label: 'Bekijk Queues en WebSocket', description: 'Lees de technische blokken onderaan wanneer een specialist daarom vraagt.' },
        { label: 'Herlaad voor een nieuwe controle', description: 'De pagina heeft geen aparte verversknop; herlaad de browserpagina.' },
      ],
      result: 'Je hebt vastgesteld welke basisdienst of instelling aandacht nodig lijkt te hebben.',
      warning: 'Ingesteld betekent niet automatisch dat achtergrondtaken of live updates echt worden verwerkt. Combineer dit scherm met een functionele test en logging.',
    },
  ],
} satisfies ManualGuideMap;
