import type { ManualGuideMap } from '../manualTypes';

export const operationManualGuides = {
  dashboard: [
    {
      id: 'dashboard-read-overview',
      title: 'Het operationele overzicht gebruiken',
      intro: 'Begin hier om snel te zien waar aandacht nodig is.',
      steps: [
        { label: 'Open Dashboard', description: 'Kies Dashboard in het menu onder Overzicht.' },
        { label: 'Controleer open meldingen', description: 'Bekijk hoeveel incidenten actief zijn en welke meldingen nog opvolging nodig hebben.' },
        { label: 'Controleer reacties', description: 'Bekijk hoeveel mensen komen, niet komen of nog niet hebben gereageerd.' },
        { label: 'Controleer beschikbaarheid en middelen', description: 'Gebruik de tellingen om te bepalen of voldoende mensen en inzetklare middelen beschikbaar zijn.' },
        { label: 'Open de betreffende melding', description: 'Klik op een incident om naar de volledige incidentdetailpagina te gaan.' },
      ],
      result: 'Je gaat vanuit het overzicht direct verder met het incident of onderdeel dat aandacht nodig heeft.',
      warning: 'Het dashboard is een operationele momentopname van beperkte recente lijsten, geen volledige organisatierapportage. Herlaad de pagina wanneer live updates niet zichtbaar binnenkomen.',
    },
  ],
  incidents: [
    {
      id: 'incident-create',
      title: 'Een incident aanmaken',
      intro: 'Leg de melding eerst volledig als incident vast.',
      permissions: ['incidents.manage'],
      prerequisites: ['Bepaal welke teams mogelijk nodig zijn.', 'Verzamel melder, telefoonnummer en locatie voor zover deze bekend zijn.'],
      steps: [
        { label: 'Open Actieve meldingen', description: 'Kies Actieve meldingen en daarna Incident aanmaken.' },
        { label: 'Vul titel en details in', description: 'Geef een herkenbare titel en leg de kern van de melding vast.' },
        { label: 'Vul melder en aanvrager in', description: 'Naam en telefoonnummer van de melder zijn vaste velden. Vul ze in wanneer bekend en vul ook de aanvragende organisatie en contactpersoon in.' },
        { label: 'Zoek de locatie', description: 'Typ een adres of herkenbare naam, kies de juiste suggestie en controleer plaats en kaart.' },
        { label: 'Kies prioriteit, teams en benodigde mensen', description: 'Selecteer de operationele teams en vul de gevraagde bezetting in.' },
        { label: 'Vul overige verplichte velden in', description: 'Velden met een ster of verplichte melding moeten zijn ingevuld voordat je kunt opslaan.' },
        { label: 'Kies Incident aanmaken', description: 'DIS slaat het incident op en opent daarna de detailpagina.' },
      ],
      result: 'Het incident bestaat als Concept. Vanuit de detailpagina kun je controleren, vooraankondigen of direct alarmeren.',
      warning: 'Een concept verstuurt niets. Controleer locatie, teams en aantallen voordat je een melding verstuurt.',
    },
    {
      id: 'incident-edit',
      title: 'Incidentgegevens of status aanpassen',
      intro: 'Werk een bestaande melding bij zonder een nieuw incident te maken.',
      permissions: ['incidents.manage'],
      steps: [
        { label: 'Open het incident', description: 'Kies het incident in Actieve meldingen of Archief.' },
        { label: 'Kies Aanpassen', description: 'De pagina Incident aanpassen opent met de huidige gegevens.' },
        { label: 'Wijzig alleen wat nodig is', description: 'Pas velden, teams, locatie, prioriteit of status aan.' },
        { label: 'Vul Reden statuswijziging in', description: 'Leg bij een statuswijziging kort uit waarom de status verandert.' },
        { label: 'Kies Incident opslaan', description: 'Na opslaan ga je terug naar het incident.' },
      ],
      result: 'De nieuwe gegevens staan op de detailpagina en de wijziging wordt in de incidentlog vastgelegd.',
      warning: 'Een statuswijziging kan direct meldingen versturen. Gebruik voor de normale route de knoppen Vooraankondiging, Direct alarmeren of Melding versturen op de detailpagina en controleer daar eerst de ontvangers.',
    },
    {
      id: 'incident-add-note',
      title: 'Een meldkamerkladblokregel toevoegen',
      intro: 'Leg vrije operationele informatie als nieuwe logregel vast.',
      permissions: ['incidents.manage'],
      steps: [
        { label: 'Open het actieve incident', description: 'Ga op de detailpagina naar Meldkamer kladblok.' },
        { label: 'Schrijf een nieuwe regel', description: 'Vul alleen de nieuwe informatie in bij Nieuwe kladblokregel.' },
        { label: 'Kies Kladblok verzenden', description: 'Wacht op de bevestiging dat de regel is toegevoegd.' },
        { label: 'Controleer de tijdlijn', description: 'De verzonden tekst staat als aparte regel in de incidentlog. Het invoerveld is weer leeg.' },
      ],
      result: 'De informatie blijft als aparte regel met tijd bij het incident bewaard en is niet zichtbaar in de mobiele operator-app. De uitvoerder staat wel in de auditregistratie.',
    },
    {
      id: 'incident-close-cancel',
      title: 'Een incident afronden of annuleren',
      intro: 'Verplaats een inzet pas naar het archief wanneer deze echt klaar is of niet doorgaat.',
      permissions: ['incidents.manage'],
      steps: [
        { label: 'Open het incident en kies Aanpassen', description: 'Controleer eerst opkomst, tijdlijn en openstaande inzetrapporten.' },
        { label: 'Kies de eindstatus', description: 'Kies Afgerond voor een uitgevoerde inzet of Geannuleerd wanneer de inzet niet doorgaat.' },
        { label: 'Vul de reden in', description: 'Leg bij Reden statuswijziging duidelijk vast waarom je afsluit of annuleert.' },
        { label: 'Kies Incident opslaan', description: 'DIS sluit het incident en brengt je terug naar de detailpagina.' },
        { label: 'Controleer Archief en Rapporten', description: 'Het incident staat voortaan in Archief. De rapportmomentopname wordt voorbereid voor snelle download.' },
      ],
      result: 'Het incident is niet meer actief. Betrokken gebruikers kunnen hun inzetrapport nog afronden zolang dat nodig is.',
      warning: 'Alleen Actief naar Geannuleerd verstuurt nu automatisch de annuleringspush van een vooraankondiging. Bij annuleren vanuit Alarmeren of In uitvoering moet de meldkamer betrokken gebruikers ook via een goedgekeurd ander kanaal informeren.',
    },
    {
      id: 'incident-delete',
      title: 'Een foutief incident permanent verwijderen',
      intro: 'Gebruik verwijderen alleen voor een onterecht of foutief aangemaakt incident.',
      permissions: ['incidents.delete'],
      steps: [
        { label: 'Open het juiste incident', description: 'Controleer referentie, titel, status en locatie.' },
        { label: 'Kies Verwijderen', description: 'De browser toont welke gekoppelde gegevens ook verdwijnen.' },
        { label: 'Lees de waarschuwing volledig', description: 'Controleer nogmaals dat dit niet alleen een incident is dat naar Archief hoort.' },
        { label: 'Bevestig permanent verwijderen', description: 'Na bevestigen keert een actief incident terug naar Actieve meldingen en een archiefincident naar Archief.' },
      ],
      result: 'Het incident en de gekoppelde operationele gegevens zijn verwijderd.',
      warning: 'Opkomst, tijdlijn, live locaties en opgeslagen rapportgegevens worden ook gewist. Dit kan niet worden teruggedraaid en verstuurt geen annuleringsmelding. Annuleer een echte inzet dus vóór verwijderen.',
    },
    {
      id: 'incident-download-pdf',
      title: 'Het bewaarde incidentrapport downloaden',
      intro: 'Open snel de PDF zonder kaarten opnieuw op te bouwen.',
      steps: [
        { label: 'Open een afgerond of geannuleerd incident', description: 'Gebruik Archief of open het incident vanuit Rapporten.' },
        { label: 'Kies Rapport PDF', description: 'Wacht terwijl de bewaarde rapportmomentopname wordt opgehaald.' },
        { label: 'Open het gedownloade bestand', description: 'Controleer incidentgegevens, kaarten, opkomst, inzetinformatie en log.' },
      ],
      result: 'Je hebt de opgeslagen PDF-momentopname die bij dit incident hoort.',
      warning: 'Controleer op Rapporten eerst Rapportstatus. Een Concept-PDF kan nog wijzigen wanneer inzetrapporten binnenkomen. Pas bij Definitief wordt de opgeslagen PDF niet meer opnieuw opgebouwd.',
    },
  ],
  dispatch: [
    {
      id: 'dispatch-preannounce',
      title: 'Een vooraankondiging versturen',
      intro: 'Vraag eerst wie beschikbaar is zonder iemand als opkomend te registreren.',
      permissions: ['incidents.view', 'incidents.manage', 'incidents.dispatch.view'],
      steps: [
        { label: 'Open een incident met status Concept', description: 'Ga naar het blok Concept op de incidentdetailpagina.' },
        { label: 'Kies het gewenste aantal', description: 'Vul bij de ETA-ringen in hoeveel mensen nodig zijn. DIS gebruikt de globale woonplaats, rekent met ongeveer 60 km/u en vergroot de geschatte ring per 15 minuten.' },
        { label: 'Lees de ontvangerscontrole', description: 'Controleer welke teams leeg zijn, hoeveel mensen geschikt zijn en welke waarschuwingen worden getoond.' },
        { label: 'Kies Vooraankondiging', description: 'De knop is uitgeschakeld wanneer geen ontvangers kunnen worden bereikt.' },
        { label: 'Volg de reacties', description: 'In Opkomst en alarmering zie je Beschikbaar, Niet beschikbaar en Nog geen reactie.' },
      ],
      result: 'De geselecteerde gebruikers beantwoorden alleen of zij beschikbaar zijn. Dit telt nog niet als opkomst en vraagt geen live locatie.',
      warning: 'ETA is een globale schatting zonder wegennet, verkeer of live route. Een lege of volledig onbereikbare selectie mag niet worden verzonden. Bij meerdere teams kan de uiteindelijke selectie afwijken van de voorvertoning; controleer de ontvangers na verzending.',
    },
    {
      id: 'dispatch-send-alarm',
      title: 'Direct of na vooraankondiging alarmeren',
      intro: 'Stuur de echte inzetmelding naar de gekozen ontvangers.',
      permissions: ['incidents.view', 'incidents.manage', 'incidents.dispatch.view'],
      steps: [
        { label: 'Controleer incident en teams', description: 'Controleer titel, plaats, prioriteit, teams en benodigde bezetting.' },
        { label: 'Controleer de ETA-ringen', description: 'Kies het gewenste aantal en lees hoeveel ontvangers werkelijk beschikbaar en online zijn.' },
        { label: 'Kies de juiste verzendknop', description: 'Gebruik Direct alarmeren vanuit Concept. Na een vooraankondiging gebruik je Melding versturen in Alarmeringsconcept.' },
        { label: 'Controleer Opkomst en alarmering', description: 'Volg Komt, Komt niet, Nog geen reactie, Onderweg en Op locatie.' },
        { label: 'Controleer live locatie afzonderlijk', description: 'Live locatie is per gebruiker opt-in en start niet alleen doordat iemand Komt kiest.' },
      ],
      result: 'Ontvangers krijgen de echte alarmering en kunnen hun opkomstreactie geven.',
      warning: 'Stuur niet opnieuw om extra mensen te zoeken. Gebruik daarvoor Opschalen; gebruik Heralarmeren alleen voor bestaande ontvangers zonder reactie.',
    },
    {
      id: 'dispatch-escalate',
      title: 'Een incident opschalen',
      intro: 'Voeg extra teams toe wanneer meer mensen of middelen nodig zijn.',
      permissions: ['incidents.dispatch.manage'],
      steps: [
        { label: 'Kies Opschalen', description: 'Open in Opkomst en alarmering het venster Incident opschalen.' },
        { label: 'Controleer huidige en al gealarmeerde teams', description: 'Gebruik de samenvatting om dubbele keuzes te voorkomen.' },
        { label: 'Vink Extra teams aan', description: 'Kies een of meer operationele teams die nog niet zijn gealarmeerd.' },
        { label: 'Kies zo nodig niet-beschikbare leden', description: 'Alleen bij een urgent incident kun je Ook niet-beschikbare teamleden alarmeren aanvinken. Push en certificaten blijven verplicht.' },
        { label: 'Kies Opschalen', description: 'DIS koppelt de teams en verstuurt direct een extra alarmering.' },
      ],
      result: 'Nieuwe geschikte ontvangers worden toegevoegd. Gebruikers die al Komt hebben gekozen hoeven niet opnieuw te reageren.',
      warning: 'Na opschalen toont Opkomst en alarmering momenteel alleen de nieuwste alarmering. Houd eerdere teams en reacties daarom apart in het oog.',
    },
    {
      id: 'dispatch-realert',
      title: 'Ontvangers zonder reactie heralarmeren',
      intro: 'Herinner alleen mensen die al in deze alarmering staan.',
      permissions: ['incidents.dispatch.manage'],
      steps: [
        { label: 'Controleer Nog geen reactie', description: 'Heralarmeren is alleen beschikbaar wanneer minstens een bestaande ontvanger nog wacht.' },
        { label: 'Kies Heralarmeren', description: 'DIS verstuurt opnieuw naar de ontvangers met Wacht op reactie.' },
        { label: 'Volg de live reacties', description: 'De lijst wordt bijgewerkt zodra gebruikers reageren.' },
      ],
      result: 'Bestaande ontvangers zonder reactie krijgen opnieuw een melding. Er worden geen nieuwe personen toegevoegd.',
    },
    {
      id: 'dispatch-correct-response',
      title: 'Een telefonische reactie of opkomst corrigeren',
      intro: 'Werk de registratie bij wanneer iemand buiten de app reageert.',
      permissions: ['incidents.dispatch.manage'],
      steps: [
        { label: 'Zoek de gebruiker', description: 'Ga in Opkomst en alarmering naar de juiste ontvanger.' },
        { label: 'Pas de reactie aan', description: 'Kies Wacht op reactie, Komt, Komt niet of Geen reactie in de keuzelijst.' },
        { label: 'Controleer de nieuwe telling', description: 'De samenvatting boven de lijst wordt na de wijziging bijgewerkt.' },
      ],
      result: 'De geregistreerde reactie sluit weer aan op wat de gebruiker telefonisch heeft doorgegeven.',
      warning: 'Rond reactiecorrecties af vóór het laatste inzetrapport definitief wordt gemaakt. Een definitieve incident-PDF wordt daarna niet opnieuw opgebouwd.',
    },
    {
      id: 'dispatch-correct-arrival',
      title: 'Onderweg of Op locatie namens iemand vastleggen',
      intro: 'Corrigeer de operationele status van iemand die Komt heeft gekozen.',
      permissions: ['status.override'],
      steps: [
        { label: 'Zoek een geaccepteerde ontvanger', description: 'De knoppen staan alleen bij een echte alarmering en een gebruiker met reactie Komt.' },
        { label: 'Kies Onderweg', description: 'Gebruik deze knop zodra de gebruiker naar het incident vertrekt.' },
        { label: 'Kies later Op locatie', description: 'Gebruik Op locatie zodra de gebruiker is aangekomen.' },
        { label: 'Controleer de statuspillen', description: 'De nieuwe operationele status verschijnt direct in de ontvangerslijst.' },
      ],
      result: 'Bij Op locatie stopt actieve locatiedeling en wordt het inzetrapport voor de gebruiker voorbereid.',
      warning: 'Zet iemand die al Op locatie staat niet terug naar Onderweg zonder een echte operationele reden.',
    },
    {
      id: 'dispatch-extra-info-location',
      title: 'Nadere informatie sturen of locatie vragen',
      intro: 'Vul een lopende inzet aan zonder een nieuw alarm te maken.',
      permissions: ['incidents.dispatch.manage'],
      steps: [
        { label: 'Stuur nadere informatie', description: 'Vul Nadere info voor opkomende gebruikers in en kies Info versturen. Alleen betrokken opkomende gebruikers ontvangen dit.' },
        { label: 'Ga naar Live locaties', description: 'Controleer per gebruiker Locatie, ETA en Laatst gezien.' },
        { label: 'Kies Vraag locatie', description: 'Gebruik de knop alleen wanneer nog geen actuele live locatie wordt gedeeld.' },
        { label: 'Wacht op toestemming', description: 'De gebruiker kiest zelf of live locatie wordt gedeeld. De status verandert pas na die reactie.' },
      ],
      result: 'Nadere info verschijnt als normale pushmelding. Een locatieverzoek start alleen delen na toestemming van de gebruiker.',
    },
  ],
  'test-alert': [
    {
      id: 'test-alert-send',
      title: 'Een handmatige proefalarmering doen',
      intro: 'Controleer push, geluid en de ontvangstknop zonder een inzet te starten.',
      permissions: ['incidents.dispatch.view', 'incidents.dispatch.manage'],
      steps: [
        { label: 'Open Proefalarmering', description: 'Kies Proefalarmering in het menu.' },
        { label: 'Kies Proefalarmering doen', description: 'DIS stuurt de proefmelding naar je eigen actieve gekoppelde toestellen.' },
        { label: 'Open de melding op het toestel', description: 'De proefmelding toont alleen de knop Ontvangen en geen opkomstknoppen.' },
        { label: 'Kies Ontvangen', description: 'Ga terug naar de webapp en controleer Live status.' },
      ],
      result: 'Je ziet voor jouw gebruiker of en wanneer de laatste proefmelding is bevestigd. De webapp toont geen aparte ontvangstregel per toestel.',
    },
    {
      id: 'test-alert-schedule',
      title: 'Het automatische proefalarm plannen',
      intro: 'Laat DIS wekelijks een vaste pushcontrole uitvoeren.',
      permissions: ['incidents.dispatch.view', 'incidents.dispatch.manage'],
      steps: [
        { label: 'Ga naar Automatisch proefalarm', description: 'Vink Automatische proefalarmering inschakelen aan.' },
        { label: 'Kies Dag en Tijd', description: 'Kies het wekelijkse controlemoment.' },
        { label: 'Vul Tekst in', description: 'Schrijf een korte herkenbare proefmelding.' },
        { label: 'Kies Planning opslaan', description: 'Controleer daarna Laatste automatische uitvoering.' },
      ],
      result: 'Actieve gebruikers met operator-app en push ontvangen het proefalarm op het ingestelde moment.',
    },
  ],
  map: [
    {
      id: 'map-use-layers',
      title: 'Kaartlagen aan- en uitzetten',
      intro: 'Toon alleen de informatie die je op dat moment nodig hebt.',
      steps: [
        { label: 'Open Kaart', description: 'Kies Kaart in het menu onder Operatie.' },
        { label: 'Kies Lagen', description: 'Het lagenmenu toont Meldkamers, Eerdere inzetten en eventueel Woonplaatsen piloten.' },
        { label: 'Zet lagen aan of uit', description: 'Meldkamers staan standaard aan. Klik op een laag om de markeringen te tonen of te verbergen.' },
        { label: 'Kies Verversen wanneer nodig', description: 'Open meldingen en locaties verversen ongeveer elke tien seconden. Verversen laadt ook de lagen opnieuw.' },
      ],
      result: 'De kaart toont de gekozen combinatie van operationele markeringen.',
      warning: 'De lagenkeuze wordt niet bewaard. Na opnieuw openen staat alleen Meldkamers standaard aan.',
    },
    {
      id: 'map-follow-incident',
      title: 'Een incident en gebruikers op de kaart volgen',
      intro: 'Bekijk wie naar welk incident gaat en open de details.',
      steps: [
        { label: 'Herken de incidentmarkering', description: 'Incidenten hebben een eigen kleur. Lijnen koppelen gedeelde gebruikerslocaties aan hetzelfde incident.' },
        { label: 'Controleer de incidentkaart onder de kaart', description: 'Bekijk titel, locatie en urgentie van het incident.' },
        { label: 'Open het incident', description: 'Klik op de incidenttitel om de detailpagina te openen.' },
        { label: 'Gebruik Fullscreen', description: 'Kies Fullscreen voor het grootste kaartbeeld en Normaal om terug te keren.' },
      ],
      result: 'Je kunt vanuit het live kaartbeeld direct naar de operationele incidentinformatie.',
    },
    {
      id: 'map-show-homes',
      title: 'Globale woonplaatsen tonen',
      intro: 'Gebruik woonplaatsen voor een globale inschatting, niet als live positie.',
      permissions: ['operational-map.pilot-homes.view'],
      steps: [
        { label: 'Open Lagen', description: 'Kies op de kaart de knop Lagen.' },
        { label: 'Zet Woonplaatsen piloten aan', description: 'De kaart toont afgeronde, globale woonplaatsposities van operationele appgebruikers.' },
        { label: 'Vergelijk met de incidentlocatie', description: 'Gebruik dit alleen als globale ondersteuning bij de inzetinschatting.' },
      ],
      result: 'Je ziet globale woonplaatsen zonder exacte woonadressen te tonen.',
      warning: 'Een woonplaats is geen live locatie en de werkelijke reistijd kan afwijken.',
    },
  ],
  status: [
    {
      id: 'status-read-overview',
      title: 'Beschikbaarheid en online status bekijken',
      intro: 'Lees in een compacte tabel wie op dit moment inzetbaar is.',
      steps: [
        { label: 'Open Status', description: 'Kies Status in het menu onder Operatie.' },
        { label: 'Controleer de tellingen', description: 'Bekijk onder meer Beschikbaar, Online, Wordt later beschikbaar en Op locatie.' },
        { label: 'Bekijk Beschikbaar per team', description: 'Wanneer teamindeling wordt getoond, lees je beschikbaar/totaal en online per team. Een gebruiker kan in meerdere teams meetellen.' },
        { label: 'Lees de gebruikerstabel', description: 'Controleer Online, Status, Weer beschikbaar en Laatst gewijzigd.' },
      ],
      result: 'Je ziet wie nu bereikbaar en beschikbaar is en wanneer iemand later terugkeert.',
      warning: 'Offline gebruikers worden als niet beschikbaar behandeld en horen niet te worden gealarmeerd. Staat er Geen teamindeling gevonden, gebruik de gebruikerstabel en teampagina; de teamsamenvatting bevat dan geen bruikbare gegevens.',
    },
    {
      id: 'status-override',
      title: 'Een gebruikersstatus namens de meldkamer wijzigen',
      intro: 'Corrigeer alleen wanneer de registratie niet overeenkomt met de werkelijkheid.',
      permissions: ['status.override'],
      steps: [
        { label: 'Zoek de gebruiker', description: 'Kies in de kolom Actie de knop Status.' },
        { label: 'Controleer naam en e-mailadres', description: 'Deze velden zijn alleen-lezen zodat je zeker weet wie je wijzigt.' },
        { label: 'Kies de nieuwe status', description: 'Kies bijvoorbeeld Beschikbaar, Niet beschikbaar, Toegewezen, Op locatie, Rust of Geblokkeerd.' },
        { label: 'Vul Reden in', description: 'Leg kort vast waarom de meldkamer deze correctie uitvoert.' },
        { label: 'Kies Opslaan', description: 'De tabel wordt daarna met de nieuwe status bijgewerkt.' },
      ],
      result: 'De statuswijziging wordt direct toegepast en in de statusaudit vastgelegd.',
      warning: 'Op locatie stopt locatiedeling en kan inzetrapportage worden voorbereid. Gebruik deze status daarom alleen bij echte aankomst. Beschikbaar en Niet beschikbaar kunnen binnen een minuut weer door het actuele beschikbaarheidsdagdeel worden toegepast.',
    },
  ],
  reports: [
    {
      id: 'reports-find-missing',
      title: 'Ontbrekende inzetrapporten vinden',
      intro: 'Zie per incident wie nog moet invullen of definitief maken.',
      steps: [
        { label: 'Open Rapporten', description: 'Kies Rapporten in het menu.' },
        { label: 'Bekijk de bovenste tellingen', description: 'Vluchtrapporten missen laat zien hoeveel rapporten nog niet zijn ingediend.' },
        { label: 'Zoek het incident', description: 'Gebruik de tabel Incidentrapporten en controleer Vluchtrapporten en Status inzetrapporten.' },
        { label: 'Lees de naamknoppen', description: 'Naam invullen betekent ontbrekend. Naam definitief maken betekent ingediend maar nog wijzigbaar.' },
      ],
      result: 'Je weet precies welk rapport en welke gebruiker nog opvolging nodig heeft.',
      warning: 'Vluchtrapporten missen telt alleen nog niet ingediende rapporten. Een ingediend maar nog niet definitief rapport staat apart als wijzigbaar. De vier bovenste rapporttellers zijn gebaseerd op maximaal de 50 nieuwste gesloten incidenten.',
    },
    {
      id: 'reports-fill-for-user',
      title: 'Een inzetrapport namens een gebruiker invullen',
      intro: 'Verwerk informatie die bijvoorbeeld telefonisch is doorgegeven.',
      permissions: ['incidents.manage'],
      steps: [
        { label: 'Kies de naam met invullen', description: 'De pagina Inzetrapport invullen opent met Namens en de incidentreferentie.' },
        { label: 'Vul alle verplichte velden in', description: 'Volg het formulier zoals dit onder Formulieren is ingesteld.' },
        { label: 'Kies Rapport opslaan', description: 'De invoer wordt als ingediend opgeslagen.' },
        { label: 'Controleer de status op Rapporten', description: 'De naam verandert van ontbrekend naar ingediend en kan daarna definitief worden gemaakt.' },
      ],
      result: 'Het inzetrapport krijgt direct status Ingediend en de Concept-PDF wordt met de nieuwe inzetinformatie bijgewerkt.',
      warning: 'Rapport opslaan is geen conceptopslag: het dient het rapport meteen in. Annuleren en Terug naar rapporten bewaren niet-opgeslagen invoer niet.',
    },
    {
      id: 'reports-edit-finalize',
      title: 'Een ingediend rapport aanpassen en definitief maken',
      intro: 'Controleer de inhoud voordat verdere wijzigingen worden geblokkeerd.',
      permissions: ['incidents.manage'],
      steps: [
        { label: 'Kies de naam met definitief maken', description: 'Het ingediende rapport opent en blijft nog wijzigbaar.' },
        { label: 'Pas zo nodig velden aan', description: 'Wijzig de gegevens en kies Rapport opslaan.' },
        { label: 'Controleer de complete inhoud', description: 'Vergelijk de informatie zo nodig met de gebruiker en het incident.' },
        { label: 'Kies Definitief maken', description: 'Wacht op de bevestiging Inzetrapport is definitief gemaakt.' },
      ],
      result: 'Het inzetrapport kan niet meer worden aangepast. Als alle vereiste rapporten definitief zijn, wordt het incidentrapport automatisch definitief.',
      warning: 'Definitief maken gebeurt direct zonder extra bevestigingsvenster en kan niet worden teruggedraaid. Controleer ook alle opkomstcorrecties voordat je het laatste rapport definitief maakt.',
    },
    {
      id: 'reports-download-statistics',
      title: 'Een PDF downloaden of alarmeringscijfers bekijken',
      intro: 'Gebruik rapportage voor dossieropbouw en verbetering van de respons.',
      steps: [
        { label: 'Download de incident-PDF', description: 'Kies in de incidentrij de knop PDF. De bewaarde rapportmomentopname wordt opgehaald.' },
        { label: 'Kies het aantal laatste meldingen', description: 'Selecteer bij Statistieken 5, 10, 25 of 50.' },
        { label: 'Lees de reactiecijfers', description: 'Bekijk Alarmeringen, Komt, Komt niet en Geen reactie.' },
        { label: 'Controleer Gebruikers zonder reactie', description: 'Bekijk per gebruiker de recente gemiste reacties en open zo nodig het incident.' },
        { label: 'Controleer Meldingen in selectie', description: 'Vergelijk per incident ontvangers en reactiepercentages.' },
      ],
      result: 'Je hebt de opgeslagen incident-PDF en een overzicht van respons over de gekozen laatste meldingen.',
      warning: 'Controleer Rapportstatus vóór verspreiding: een Concept-PDF kan nog worden vernieuwd. De keuze Laatste meldingen filtert alleen de statistieken, niet de incidenttabel of de vier rapporttellers. Herhaalde alarmeringen aan dezelfde persoon kunnen in statistieken meermaals meetellen.',
    },
  ],
} satisfies ManualGuideMap;
