import type { ManualGuideMap } from '../manualTypes';

export const operationManualGuides = {
  dashboard: [
    {
      id: 'dashboard-read-overview',
      title: 'Het operationele overzicht gebruiken',
      intro: 'Begin hier om snel te zien waar aandacht nodig is.',
      steps: [
        { label: 'Open Dashboard', description: 'Kies Dashboard in het menu onder Overzicht.' },
        { label: 'Controleer open inzetten', description: 'Bekijk hoeveel inzetten actief zijn en welke aanvragen nog opvolging nodig hebben.' },
        { label: 'Controleer reacties', description: 'Bekijk hoeveel mensen komen, niet komen of nog niet hebben gereageerd.' },
        { label: 'Controleer beschikbaarheid en middelen', description: 'Gebruik de tellingen om te bepalen of voldoende mensen en inzetklare middelen beschikbaar zijn.' },
        { label: 'Open de betreffende inzet', description: 'Klik op een inzet om naar de volledige inzetdetailpagina te gaan.' },
      ],
      result: 'Je gaat vanuit het overzicht direct verder met de inzet of het onderdeel dat aandacht nodig heeft.',
      warning: 'Het dashboard is een operationele momentopname van beperkte recente lijsten, geen volledige organisatierapportage. Herlaad de pagina wanneer live updates niet zichtbaar binnenkomen.',
    },
  ],
  deployments: [
    {
      id: 'deployment-create',
      title: 'Een inzet voorbereiden',
      intro: 'Leg de aanvraag eerst volledig vast. Iedere nieuwe inzet begint als Concept.',
      permissions: ['deployments.manage'],
      prerequisites: ['Bepaal welke teams mogelijk nodig zijn.', 'Verzamel melder, telefoonnummer en locatie voor zover deze bekend zijn.'],
      steps: [
        { label: 'Maak de aanvraag bewust aan', description: 'Open Aanvragen, kies Nieuwe aanvraag, geef een herkenbare titel, kies het onderwerp en kies Aanvraag aanmaken. Alleen deze knop legt de nieuwe aanvraag vast.' },
        { label: 'Vul de details in', description: 'Controleer de titel en leg de kern van de aanvraag vast. Wijzigingen in een bewust aangemaakt dossier worden daarna veilig tussentijds opgeslagen.' },
        { label: 'Vul melder en aanvrager in', description: 'Naam en telefoonnummer van de melder zijn vaste velden. Vul ze in wanneer bekend en vul ook de aanvragende organisatie en contactpersoon in.' },
        { label: 'Zoek de locatie', description: 'Typ een adres of herkenbare naam, kies de juiste suggestie en controleer plaats en kaart.' },
        { label: 'Kies prioriteit, teams en benodigde mensen', description: 'Selecteer de operationele teams en vul de gevraagde bezetting in.' },
        { label: 'Vul overige verplichte velden in', description: 'Velden met een ster of een verplichte markering moeten zijn ingevuld voordat je kunt opslaan.' },
        { label: 'Kies Inzet voorbereiden', description: 'Je kiest hierbij geen status. DIS slaat de inzet automatisch op als Concept en opent daarna de detailpagina.' },
      ],
      result: 'De inzet bestaat als Concept. Vanuit de detailpagina kun je de gegevens controleren en daarna Vooraankondiging of Direct alarmeren kiezen.',
      warning: 'Een concept verstuurt niets. Controleer locatie, teams en aantallen voordat je een alarmering verstuurt.',
    },
    {
      id: 'deployment-edit',
      title: 'Inzetgegevens aanpassen',
      intro: 'Werk een bestaande inzet bij zonder een nieuwe inzet te maken. Alleen een Systeembeheerder kan via Aanpassen de inzetstatus handmatig wijzigen.',
      permissions: ['deployments.manage'],
      steps: [
        { label: 'Open de inzet', description: 'Kies de inzet onder Inzetten of in het Archief.' },
        { label: 'Kies Aanpassen', description: 'De pagina Inzet aanpassen opent met de huidige gegevens.' },
        { label: 'Wijzig alleen wat nodig is', description: 'Pas bijvoorbeeld de inhoud, teams, locatie of prioriteit aan.' },
        { label: 'Wijzig de status alleen als Systeembeheerder', description: 'Alleen voor deze rol is de statuskeuze beschikbaar. Leg bij een handmatige statuswijziging in Reden statuswijziging kort uit waarom deze uitzonderingscorrectie nodig is.' },
        { label: 'Kies Inzet opslaan', description: 'Na opslaan ga je terug naar de inzet.' },
      ],
      result: 'De nieuwe gegevens staan op de detailpagina en de wijziging wordt in de inzetlog vastgelegd.',
      warning: 'Normale beheerders wijzigen de status niet via Aanpassen. Gebruik voor de normale route Vooraankondiging, Direct alarmeren of Alarmering versturen op de detailpagina en controleer daar eerst de ontvangers. Een handmatige statuswijziging door een Systeembeheerder is alleen voor een noodzakelijke correctie.',
    },
    {
      id: 'deployment-add-note',
      title: 'Een meldkamerkladblokregel toevoegen',
      intro: 'Leg vrije operationele informatie als nieuwe logregel vast.',
      permissions: ['deployments.manage'],
      steps: [
        { label: 'Open de actieve inzet', description: 'Ga op de detailpagina naar Meldkamer kladblok.' },
        { label: 'Schrijf een nieuwe regel', description: 'Vul alleen de nieuwe informatie in bij Nieuwe kladblokregel.' },
        { label: 'Kies Kladblok verzenden', description: 'Wacht op de bevestiging dat de regel is toegevoegd.' },
        { label: 'Controleer het inzetlogboek', description: 'De verzonden tekst staat als aparte regel met de handeling en de naam van de centralist. Het invoerveld is weer leeg.' },
      ],
      result: 'De informatie blijft als aparte regel met tijd en naam van de centralist bij de inzet bewaard. Kladblokregels blijven afgeschermd van de mobiele operator-app.',
    },
    {
      id: 'deployment-close-cancel',
      title: 'Een inzet afronden of annuleren',
      intro: 'Annuleer alleen een Concept of Actieve inzet die niet doorgaat. Rond een uitgevoerde inzet af zodra de status In uitvoering is.',
      permissions: ['deployments.manage'],
      steps: [
        { label: 'Open de inzet', description: 'Controleer de huidige status, opkomst, tijdlijn en eventuele openstaande inzetrapporten.' },
        { label: 'Annuleer vanuit Concept of Actief', description: 'Kies Annuleren wanneer de inzet niet doorgaat. Deze knop is alleen bij deze twee statussen beschikbaar.' },
        { label: 'Rond af vanuit In uitvoering', description: 'Kies bovenaan de detailpagina Afronden wanneer de inzet echt klaar is. Deze knop is alleen bij In uitvoering beschikbaar.' },
        { label: 'Bevestig de actie', description: 'Controleer de gekozen eindstatus en leg de gevraagde reden duidelijk vast.' },
        { label: 'Controleer Archief en Rapporten', description: 'De inzet staat voortaan in Archief. De rapportmomentopname wordt voorbereid voor snelle download.' },
      ],
      result: 'De inzet is niet meer actief. Betrokken gebruikers kunnen hun inzetrapport nog afronden zolang dat nodig is.',
      warning: 'Bij Alarmeren en In uitvoering is Annuleren niet beschikbaar. Een normale beheerder kan deze statussen niet handmatig omzetten; alleen een Systeembeheerder kan via Aanpassen een noodzakelijke statuscorrectie uitvoeren.',
    },
    {
      id: 'deployment-delete',
      title: 'Een foutieve inzet permanent verwijderen',
      intro: 'Gebruik verwijderen alleen voor een onterecht of foutief voorbereide inzet.',
      permissions: ['deployments.delete'],
      steps: [
        { label: 'Open de juiste inzet', description: 'Controleer referentie, titel, status en locatie.' },
        { label: 'Kies Verwijderen', description: 'De browser toont welke gekoppelde gegevens ook verdwijnen.' },
        { label: 'Lees de waarschuwing volledig', description: 'Controleer nogmaals dat dit niet alleen een inzet is die naar Archief hoort.' },
        { label: 'Bevestig permanent verwijderen', description: 'Na bevestigen keert een actieve inzet terug naar Inzetten en een gearchiveerde inzet naar Archief.' },
      ],
      result: 'De inzet en de gekoppelde operationele gegevens zijn verwijderd.',
      warning: 'Opkomst, tijdlijn, live locaties en opgeslagen rapportgegevens worden ook gewist. Dit kan niet worden teruggedraaid en verstuurt geen annuleringsmelding. Annuleer een echte inzet dus vóór verwijderen.',
    },
    {
      id: 'deployment-download-pdf',
      title: 'Het bewaarde inzetrapport downloaden',
      intro: 'Open snel de PDF zonder kaarten opnieuw op te bouwen.',
      steps: [
        { label: 'Open een afgeronde of geannuleerde inzet', description: 'Gebruik Archief of open de inzet vanuit Rapporten.' },
        { label: 'Kies Rapport PDF', description: 'Wacht terwijl de bewaarde rapportmomentopname wordt opgehaald.' },
        { label: 'Open het gedownloade bestand', description: 'Controleer inzetgegevens, kaarten, opkomst, inzetinformatie en log.' },
      ],
      result: 'Je hebt de opgeslagen PDF-momentopname die bij deze inzet hoort.',
      warning: 'Controleer op Rapporten eerst Rapportstatus. Een Concept-PDF kan nog wijzigen wanneer inzetrapporten binnenkomen. Pas bij Definitief wordt de opgeslagen PDF niet meer opnieuw opgebouwd.',
    },
  ],
  dispatch: [
    {
      id: 'dispatch-preannounce',
      title: 'Een vooraankondiging versturen',
      intro: 'Vraag eerst wie beschikbaar is zonder iemand als opkomend te registreren.',
      permissions: ['deployments.dispatch.view', 'deployments.dispatch.manage'],
      oneOfPermissions: ['deployments.view', 'deployments.manage'],
      steps: [
        { label: 'Open een inzet met status Concept', description: 'Ga naar het blok Concept op de inzetdetailpagina.' },
        { label: 'Kies het gewenste aantal', description: 'Vul bij de ETA-ringen in hoeveel mensen nodig zijn. DIS berekent de autoroute vanaf de globale woonplaats en rondt de navigatie-ETA naar boven af in ringen van 15 minuten.' },
        { label: 'Lees de ontvangerscontrole', description: 'Controleer welke teams leeg zijn, hoeveel mensen geschikt zijn en welke waarschuwingen worden getoond.' },
        { label: 'Kies Vooraankondiging', description: 'De knop is uitgeschakeld wanneer geen ontvangers kunnen worden bereikt.' },
        { label: 'Volg de reacties', description: 'In Opkomst en alarmering zie je Beschikbaar, Niet beschikbaar en Nog geen reactie.' },
      ],
      result: 'De inzet krijgt status Actief. De geselecteerde gebruikers beantwoorden alleen of zij beschikbaar zijn. Dit telt nog niet als opkomst en vraagt geen live locatie.',
      warning: 'De navigatie-ETA gebruikt het beschikbare wegennet, maar geen actuele verkeersinformatie. Als routering tijdelijk niet lukt, toont DIS herkenbaar een terugvalschatting. Vóór alarmering is de globale woonplaats het vertrekpunt, niet een live locatie. Een lege of volledig onbereikbare selectie mag niet worden verzonden. Bij meerdere teams kan de uiteindelijke selectie afwijken van de voorvertoning; controleer de ontvangers na verzending.',
    },
    {
      id: 'dispatch-send-alarm',
      title: 'Direct of na vooraankondiging alarmeren',
      intro: 'Stuur de echte inzetalarmering naar de gekozen ontvangers.',
      permissions: ['deployments.dispatch.view', 'deployments.dispatch.manage'],
      oneOfPermissions: ['deployments.view', 'deployments.manage'],
      steps: [
        { label: 'Controleer inzet en teams', description: 'Controleer titel, plaats, prioriteit, teams en benodigde bezetting.' },
        { label: 'Controleer de ETA-ringen', description: 'Kies het gewenste aantal en lees hoeveel ontvangers werkelijk beschikbaar en online zijn.' },
        { label: 'Kies de juiste verzendknop', description: 'Gebruik Direct alarmeren vanuit Concept. Na een vooraankondiging gebruik je Alarmering versturen in Alarmeringsconcept.' },
        { label: 'Controleer Opkomst en alarmering', description: 'Volg Komt, Komt niet, Nog geen reactie, Onderweg en Op locatie.' },
        { label: 'Controleer live locatie afzonderlijk', description: 'Live locatie is per gebruiker opt-in en start niet alleen doordat iemand Komt kiest.' },
      ],
      result: 'De inzet krijgt status Alarmeren. Ontvangers krijgen de echte alarmering en kunnen hun opkomstreactie geven.',
      warning: 'Stuur niet opnieuw om extra mensen te zoeken. Gebruik daarvoor Opschalen; gebruik Heralarmeren alleen voor bestaande ontvangers zonder reactie.',
    },
    {
      id: 'dispatch-escalate',
      title: 'Een inzet opschalen',
      intro: 'Voeg extra teams toe wanneer meer mensen of middelen nodig zijn.',
      permissions: ['deployments.dispatch.view', 'deployments.dispatch.manage'],
      oneOfPermissions: ['deployments.view', 'deployments.manage'],
      steps: [
        { label: 'Kies Opschalen', description: 'Open in Opkomst en alarmering het venster Inzet opschalen.' },
        { label: 'Controleer huidige en al gealarmeerde teams', description: 'Gebruik de samenvatting om dubbele keuzes te voorkomen.' },
        { label: 'Vink Extra teams aan', description: 'Kies een of meer operationele teams die nog niet zijn gealarmeerd.' },
        { label: 'Kies zo nodig niet-beschikbare leden', description: 'Alleen bij een urgente inzet kun je Ook niet-beschikbare teamleden alarmeren aanvinken. Push en certificaten blijven verplicht.' },
        { label: 'Kies Opschalen', description: 'DIS koppelt de teams en verstuurt direct een extra alarmering.' },
      ],
      result: 'Nieuwe geschikte ontvangers worden toegevoegd. Gebruikers die al Komt hebben gekozen hoeven niet opnieuw te reageren.',
      warning: 'Na opschalen toont Opkomst en alarmering momenteel alleen de nieuwste alarmering. Houd eerdere teams en reacties daarom apart in het oog.',
    },
    {
      id: 'dispatch-realert',
      title: 'Ontvangers zonder reactie heralarmeren',
      intro: 'Herinner alleen mensen die al in deze alarmering staan.',
      permissions: ['deployments.dispatch.view', 'deployments.dispatch.manage'],
      oneOfPermissions: ['deployments.view', 'deployments.manage'],
      steps: [
        { label: 'Controleer Nog geen reactie', description: 'Heralarmeren is alleen beschikbaar wanneer minstens een bestaande ontvanger nog wacht.' },
        { label: 'Kies Heralarmeren', description: 'DIS verstuurt opnieuw naar de ontvangers met Wacht op reactie.' },
        { label: 'Volg de live reacties', description: 'De lijst wordt bijgewerkt zodra gebruikers reageren.' },
      ],
      result: 'Bestaande ontvangers zonder reactie krijgen opnieuw een melding. Er worden geen nieuwe personen toegevoegd.',
    },
    {
      id: 'dispatch-correct-response',
      title: 'Een telefonische reactie of opkomst corrigeren',
      intro: 'Werk de registratie bij wanneer iemand buiten de app reageert.',
      permissions: ['deployments.dispatch.view', 'deployments.dispatch.manage'],
      oneOfPermissions: ['deployments.view', 'deployments.manage'],
      steps: [
        { label: 'Zoek de gebruiker', description: 'Ga in Opkomst en alarmering naar de juiste ontvanger.' },
        { label: 'Pas de reactie aan', description: 'Kies Wacht op reactie, Komt, Komt niet of Geen reactie in de keuzelijst.' },
        { label: 'Controleer de nieuwe telling', description: 'De samenvatting boven de lijst wordt na de wijziging bijgewerkt.' },
      ],
      result: 'De geregistreerde reactie sluit weer aan op wat de gebruiker telefonisch heeft doorgegeven.',
      warning: 'Rond reactiecorrecties af vóór het laatste inzetrapport definitief wordt gemaakt. Een definitieve inzet-PDF wordt daarna niet opnieuw opgebouwd.',
    },
    {
      id: 'dispatch-link-pilot',
      title: 'Een piloot handmatig aan de inzet koppelen',
      intro: 'Voeg tijdens een inzet met status Actief, Alarmeren of In uitvoering een piloot toe zonder een alarm te laten klinken.',
      permissions: ['deployments.dispatch.manage'],
      oneOfPermissions: ['deployments.view', 'deployments.manage'],
      steps: [
        { label: 'Ga naar Gekoppelde piloten', description: 'Open de inzetdetailpagina en kies Piloot koppelen.' },
        { label: 'Zoek en kies de piloot', description: 'Zoek op naam of e-mailadres en controleer de actuele status.' },
        { label: 'Leg de reden vast', description: 'Beschrijf waarom deze piloot buiten de alarmering om aan de inzet wordt toegevoegd.' },
        { label: 'Kies Piloot koppelen', description: 'De piloot wordt direct zichtbaar bij Gekoppelde piloten.' },
      ],
      result: 'De piloot is operationeel aan de inzet gekoppeld en ontvangt een informatief pushbericht. Er klinkt geen alarm.',
      warning: 'Koppelen en ontkoppelen is niet beschikbaar bij een Concept, proefinzet of gesloten inzet. Een via de alarmering gekoppelde piloot blijft onderdeel van de alarmeringsregistratie.',
    },
    {
      id: 'dispatch-correct-arrival',
      title: 'Onderweg of Op locatie namens iemand vastleggen',
      intro: 'Corrigeer de inzetgebonden operationele status van een piloot die werkelijk aan deze inzet is gekoppeld.',
      permissions: ['deployments.dispatch.manage', 'status.override'],
      anyPermission: true,
      oneOfPermissions: ['deployments.dispatch.view', 'deployments.dispatch.manage'],
      steps: [
        { label: 'Ga naar Gekoppelde piloten', description: 'Zoek de juiste handmatig of via de alarmering gekoppelde piloot.' },
        { label: 'Kies Onderweg', description: 'Gebruik deze knop zodra de gebruiker naar de inzetlocatie vertrekt.' },
        { label: 'Kies later Op locatie', description: 'Gebruik Op locatie zodra de gebruiker is aangekomen.' },
        { label: 'Controleer de statuspillen', description: 'De nieuwe operationele status verschijnt direct bij de gekoppelde piloot.' },
      ],
      result: 'De participantstatus voor deze inzet is vastgelegd. Bij Op locatie stopt actieve locatiedeling en wordt het inzetrapport voor de gebruiker voorbereid.',
      warning: 'Deze correctie is alleen beschikbaar bij Actief, Alarmeren of In uitvoering. Zet iemand die al Op locatie staat niet terug naar Onderweg zonder een echte operationele reden.',
    },
    {
      id: 'dispatch-extra-info-location',
      title: 'Nadere informatie sturen of locatie vragen',
      intro: 'Vul een lopende inzet aan zonder een nieuw alarm te maken.',
      permissions: ['deployments.dispatch.view', 'deployments.dispatch.manage'],
      oneOfPermissions: ['deployments.view', 'deployments.manage'],
      steps: [
        { label: 'Stuur nadere informatie', description: 'Vul Nadere info voor opkomende gebruikers in en kies Info versturen. Alleen betrokken opkomende gebruikers ontvangen dit.' },
        { label: 'Ga naar Live locaties', description: 'Controleer per gebruiker Locatie, navigatie-ETA en Laatst gezien. Bij een verlopen locatie wordt geen reistijd getoond; een terugvalschatting staat als Schatting gemarkeerd.' },
        { label: 'Kies Vraag locatie', description: 'Gebruik de knop alleen wanneer nog geen actuele live locatie wordt gedeeld.' },
        { label: 'Wacht op toestemming', description: 'De gebruiker kiest zelf of live locatie wordt gedeeld. De status verandert pas na die reactie.' },
      ],
      result: 'Nadere info verschijnt als normale pushmelding. Een locatieverzoek start alleen delen na toestemming van de gebruiker.',
    },
  ],
  'test-alert': [
    {
      id: 'test-alert-send',
      title: 'Een handmatige proefalarmering doen',
      intro: 'Controleer push, geluid en de ontvangstknop zonder een inzet te starten.',
      permissions: ['deployments.dispatch.view', 'deployments.dispatch.manage'],
      steps: [
        { label: 'Open Proefalarmering', description: 'Kies Proefalarmering in het menu.' },
        { label: 'Kies de ontvangers', description: 'Kies Alleen mijzelf voor je eigen actieve gekoppelde apps, of Alle bereikbare operator-apps voor een extra bereikbaarheidstest.' },
        { label: 'Bevestig een brede test', description: 'Bij Alle bereikbare operator-apps vraagt DIS om een extra bevestiging. Deze test filtert niet op beschikbaarheid, certificeringen of toegewezen drones.' },
        { label: 'Start de proefalarmering', description: 'Kies Persoonlijke proefmelding versturen of bevestig de brede bereikbaarheidstest.' },
        { label: 'Open de melding op het toestel', description: 'De proefmelding toont alleen de knop Ontvangen en geen opkomstknoppen.' },
        { label: 'Kies Ontvangen', description: 'Ga terug naar de webapp en controleer Laatste losse proefmelding.' },
      ],
      result: 'Na het starten toont DIS voor hoeveel gebruikers de melding is klaargezet, hoeveel pushmeldingen in de wachtrij staan en hoeveel gebruikers vooraf zijn overgeslagen. Wanneer een geselecteerde gebruiker door een fout op geen enkel toestel kon worden klaargezet, wordt dit apart gemeld. Alleen een bevestiging in de operator-app bewijst ontvangst; provideracceptatie alleen bewijst niet dat het toestel de melding heeft getoond.',
    },
    {
      id: 'test-alert-schedule',
      title: 'Het automatische proefalarm plannen',
      intro: 'Laat DIS wekelijks een vaste pushcontrole uitvoeren.',
      permissions: ['deployments.dispatch.view', 'deployments.dispatch.manage'],
      steps: [
        { label: 'Ga naar Automatisch proefalarm', description: 'Vink Automatische proefalarmering inschakelen aan.' },
        { label: 'Kies Dag en Tijd', description: 'Kies het wekelijkse controlemoment.' },
        { label: 'Vul Tekst in', description: 'Schrijf een korte herkenbare proefmelding.' },
        { label: 'Kies Planning opslaan', description: 'Controleer daarna Laatste automatische uitvoering.' },
      ],
      result: 'De laatste weekrun toont per geselecteerde operator of de melding is klaargezet, door de pushdienst is geaccepteerd en in de operator-app is bevestigd. Zonder bevestiging blijft toestelontvangst onbekend. De doelgroep bevat alleen actieve gebruikers met push en minimaal één actieve operatorkoppeling op het startmoment.',
    },
  ],
  map: [
    {
      id: 'map-use-layers',
      title: 'Kaartlagen aan- en uitzetten',
      intro: 'Toon alleen de informatie die je op dat moment nodig hebt.',
      steps: [
        { label: 'Open Kaart', description: 'Kies Kaart in het menu onder Operatie.' },
        { label: 'Kies Lagen', description: 'Het lagenmenu toont Meldkamers, Eerdere inzetten en eventueel Woonplaatsen piloten.' },
        { label: 'Zet lagen aan of uit', description: 'Meldkamers staan standaard aan. Klik op een laag om de markeringen te tonen of te verbergen.' },
        { label: 'Kies Verversen wanneer nodig', description: 'Open inzetten en locaties verversen ongeveer elke tien seconden. Verversen laadt ook de lagen opnieuw.' },
      ],
      result: 'De kaart toont de gekozen combinatie van operationele markeringen.',
      warning: 'De lagenkeuze wordt niet bewaard. Na opnieuw openen staat alleen Meldkamers standaard aan.',
    },
    {
      id: 'map-follow-deployment',
      title: 'Een inzet en gebruikers op de kaart volgen',
      intro: 'Bekijk wie naar welke inzet gaat en open de details.',
      steps: [
        { label: 'Herken de inzetmarkering', description: 'Inzetten hebben een eigen kleur. Lijnen koppelen gedeelde gebruikerslocaties aan dezelfde inzet.' },
        { label: 'Controleer de inzetkaart onder de kaart', description: 'Bekijk titel, locatie en urgentie van de inzet.' },
        { label: 'Open de inzet', description: 'Klik op de inzettitel om de detailpagina te openen.' },
        { label: 'Gebruik Fullscreen', description: 'Kies Fullscreen voor het grootste kaartbeeld en Normaal om terug te keren.' },
      ],
      result: 'Je kunt vanuit het live kaartbeeld direct naar de operationele inzetinformatie.',
    },
    {
      id: 'map-show-homes',
      title: 'Globale woonplaatsen tonen',
      intro: 'Gebruik woonplaatsen voor een globale inschatting, niet als live positie.',
      permissions: ['operational-map.pilot-homes.view'],
      steps: [
        { label: 'Open Lagen', description: 'Kies op de kaart de knop Lagen.' },
        { label: 'Zet Woonplaatsen piloten aan', description: 'De kaart toont afgeronde, globale woonplaatsposities van operationele appgebruikers.' },
        { label: 'Vergelijk met de inzetlocatie', description: 'Gebruik dit alleen als globale ondersteuning bij de inzetinschatting.' },
      ],
      result: 'Je ziet globale woonplaatsen zonder exacte woonadressen te tonen.',
      warning: 'Een woonplaats is geen live locatie en de werkelijke reistijd kan afwijken.',
    },
  ],
  weather: [
    {
      id: 'weather-read-live-map',
      title: 'De live radarkaart controleren',
      intro: 'Controleer live KNMI-neerslagradar en EUMETSAT-bliksemdetectie voor Nederland, België en westelijk Duitsland.',
      permissions: ['operational-weather.view'],
      steps: [
        { label: 'Open Weer', description: 'Kies Weer in het menu onder Operatie.' },
        { label: 'Kies het gebied', description: 'Laat Nederland staan of kies Adres, vul een adres of plaatsnaam in en kies Toepassen.' },
        { label: 'Gebruik de kaart', description: 'De OpenStreetMap-achtergrondkaart toont automatisch heel Nederland of de gevonden plaats. Daarna kun je vrij slepen en zoomen.' },
        { label: 'Lees de tijdlijn', description: 'De verticale NU-markering scheidt gemeten beelden van de verwachting. Gebruik de schuifregelaar, Vorige, Volgende of Afspelen.' },
        { label: 'Bekijk de bliksemradar', description: 'Kies Bliksem. EUMETSAT LI toont total lightning als geaccumuleerd bliksemflitsgebied en onderscheidt wolk-grond en wolk-wolk niet.' },
        { label: 'Controleer bron en tijd', description: 'Lees per laag de bronnaam, geldige of gemeten tijd en eventuele beschikbaarheidsmelding.' },
        { label: 'Laat de actualiteit bewaken', description: 'De zichtbare pagina controleert iedere vijf minuten op nieuwe radardata. Kies Verversen voor een directe controle.' },
      ],
      result: 'Je hebt een transparant live weerbeeld met zichtbare bron en actualiteit.',
      warning: 'De pagina Weer geeft geen vliegadvies. Onbekende of verouderde data mag niet als gunstige situatie worden geïnterpreteerd.',
    },
  ],
  'uav-forecast': [
    {
      id: 'uav-forecast-assess',
      title: 'Een UAV Forecast beoordelen',
      intro: 'Begin bij het serveradvies en controleer daarna alle onderliggende waarden en bronnen.',
      permissions: ['uav-forecast.view'],
      steps: [
        { label: 'Open UAV Forecast', description: 'Kies UAV Forecast in het menu onder Operatie.' },
        { label: 'Kies het gebied', description: 'Gebruik Nederland of kies Adres en laat de server het ingevoerde adres of de plaatsnaam vinden.' },
        { label: 'Lees het vliegadvies', description: 'Binnen standaarddrempels, Extra beoordeling vereist, Niet vliegen of Advies onvolledig is door de server bepaald.' },
        { label: 'Controleer iedere waarde', description: 'Lees status, waarde, toelichting, bron en meet- of modeltijd. Baseer een vluchtbesluit nooit alleen op de hoofdkleur.' },
        { label: 'Controleer reikwijdte en disclaimer', description: 'Lees welke gegevens wel en niet in de forecast zitten en betrek de actuele lokale omstandigheden.' },
        { label: 'Ververs indien nodig', description: 'De pagina controleert bij zichtbaarheid ongeveer iedere vijftien minuten. Kies Verversen voor een directe nieuwe berekening.' },
      ],
      result: 'Je hebt het centrale advies en alle zichtbare standaardwaarden met hun herkomst beoordeeld.',
      warning: 'Ontbrekende, ongeldige of verouderde noodzakelijke data is nooit groen. De forecast ondersteunt de operationele afweging maar vervangt die niet.',
    },
  ],
  status: [
    {
      id: 'status-read-overview',
      title: 'Beschikbaarheid en online status bekijken',
      intro: 'Lees in een compacte tabel wie op dit moment inzetbaar is.',
      steps: [
        { label: 'Open Status', description: 'Kies Status in het menu onder Operatie.' },
        { label: 'Controleer de tellingen', description: 'Bekijk onder meer Beschikbaar, Online, Wordt later beschikbaar en Op locatie.' },
        { label: 'Bekijk Beschikbaar per team', description: 'Wanneer teamindeling wordt getoond, lees je beschikbaar/totaal en online per team. Een gebruiker kan in meerdere teams meetellen.' },
        { label: 'Lees de gebruikerstabel', description: 'Controleer Online, Status, Weer beschikbaar en Laatst gewijzigd.' },
      ],
      result: 'Je ziet wie nu bereikbaar en beschikbaar is en wanneer iemand later terugkeert.',
      warning: 'Offline gebruikers worden als niet beschikbaar behandeld en horen niet te worden gealarmeerd. Staat er Geen teamindeling gevonden, gebruik de gebruikerstabel en teampagina; de teamsamenvatting bevat dan geen bruikbare gegevens.',
    },
    {
      id: 'status-override',
      title: 'Een gebruikersstatus namens de meldkamer wijzigen',
      intro: 'Corrigeer alleen wanneer de registratie niet overeenkomt met de werkelijkheid.',
      permissions: ['status.override'],
      steps: [
        { label: 'Zoek de gebruiker', description: 'Kies in de kolom Actie de knop Status.' },
        { label: 'Controleer naam en e-mailadres', description: 'Deze velden zijn alleen-lezen zodat je zeker weet wie je wijzigt.' },
        { label: 'Kies de nieuwe status', description: 'Kies bijvoorbeeld Beschikbaar, Niet beschikbaar, Toegewezen, Op locatie, Rust of Geblokkeerd.' },
        { label: 'Vul Reden in', description: 'Leg kort vast waarom de meldkamer deze correctie uitvoert.' },
        { label: 'Kies Opslaan', description: 'De tabel wordt daarna met de nieuwe status bijgewerkt.' },
      ],
      result: 'De statuswijziging wordt direct toegepast en in de statusaudit vastgelegd.',
      warning: 'Op locatie stopt locatiedeling en kan inzetrapportage worden voorbereid. Gebruik deze status daarom alleen bij echte aankomst. Beschikbaar en Niet beschikbaar kunnen binnen een minuut weer door het actuele beschikbaarheidsdagdeel worden toegepast.',
    },
  ],
  reports: [
    {
      id: 'reports-find-missing',
      title: 'Ontbrekende inzetrapporten vinden',
      intro: 'Zie per inzet wie nog moet invullen of definitief maken.',
      steps: [
        { label: 'Open Rapporten', description: 'Kies Rapporten in het menu.' },
        { label: 'Bekijk de bovenste tellingen', description: 'Vluchtrapporten missen laat zien hoeveel rapporten nog niet zijn ingediend.' },
        { label: 'Zoek de inzet', description: 'Gebruik de tabel Inzetrapporten en controleer Vluchtrapporten en Status inzetrapporten.' },
        { label: 'Lees de naamknoppen', description: 'Naam invullen betekent ontbrekend. Naam definitief maken betekent ingediend maar nog wijzigbaar.' },
      ],
      result: 'Je weet precies welk rapport en welke gebruiker nog opvolging nodig heeft.',
      warning: 'Vluchtrapporten missen telt alleen nog niet ingediende rapporten. Een ingediend maar nog niet definitief rapport staat apart als wijzigbaar. De vier bovenste rapporttellers zijn gebaseerd op maximaal de 50 nieuwste gesloten inzetten.',
    },
    {
      id: 'reports-fill-for-user',
      title: 'Een inzetrapport namens een gebruiker invullen',
      intro: 'Verwerk informatie die bijvoorbeeld telefonisch is doorgegeven.',
      permissions: ['deployments.manage'],
      steps: [
        { label: 'Kies de naam met invullen', description: 'De pagina Inzetrapport invullen opent met Namens en de inzetreferentie.' },
        { label: 'Vul alle verplichte velden in', description: 'Volg het formulier zoals dit onder Formulieren is ingesteld.' },
        { label: 'Kies Rapport opslaan', description: 'De invoer wordt als ingediend opgeslagen.' },
        { label: 'Controleer de status op Rapporten', description: 'De naam verandert van ontbrekend naar ingediend en kan daarna definitief worden gemaakt.' },
      ],
      result: 'Het inzetrapport krijgt direct status Ingediend en de Concept-PDF wordt met de nieuwe inzetinformatie bijgewerkt.',
      warning: 'Rapport opslaan is geen conceptopslag: het dient het rapport meteen in. Annuleren en Terug naar rapporten bewaren niet-opgeslagen invoer niet.',
    },
    {
      id: 'reports-edit-finalize',
      title: 'Een ingediend rapport aanpassen en definitief maken',
      intro: 'Controleer de inhoud voordat verdere wijzigingen worden geblokkeerd.',
      permissions: ['deployments.manage'],
      steps: [
        { label: 'Kies de naam met definitief maken', description: 'Het ingediende rapport opent en blijft nog wijzigbaar.' },
        { label: 'Pas zo nodig velden aan', description: 'Wijzig de gegevens en kies Rapport opslaan.' },
        { label: 'Controleer de complete inhoud', description: 'Vergelijk de informatie zo nodig met de gebruiker en de inzet.' },
        { label: 'Kies Definitief maken', description: 'Wacht op de bevestiging Inzetrapport is definitief gemaakt.' },
      ],
      result: 'Het inzetrapport kan niet meer worden aangepast. Als alle vereiste rapporten definitief zijn, wordt de inzetrapportage automatisch definitief.',
      warning: 'Definitief maken gebeurt direct zonder extra bevestigingsvenster en kan niet worden teruggedraaid. Controleer ook alle opkomstcorrecties voordat je het laatste rapport definitief maakt.',
    },
    {
      id: 'reports-download-statistics',
      title: 'Een PDF downloaden of alarmeringscijfers bekijken',
      intro: 'Gebruik rapportage voor dossieropbouw en verbetering van de respons.',
      steps: [
        { label: 'Download de inzet-PDF', description: 'Kies in de inzetrij de knop PDF. De bewaarde rapportmomentopname wordt opgehaald.' },
        { label: 'Kies het aantal laatste alarmeringen', description: 'Selecteer bij Statistieken 5, 10, 25 of 50.' },
        { label: 'Lees de reactiecijfers', description: 'Bekijk Alarmeringen, Komt, Komt niet en Geen reactie.' },
        { label: 'Controleer Gebruikers zonder reactie', description: 'Bekijk per gebruiker de recente gemiste reacties en open zo nodig de inzet.' },
        { label: 'Controleer alarmeringen in selectie', description: 'Vergelijk per inzet ontvangers en reactiepercentages.' },
      ],
      result: 'Je hebt de opgeslagen inzet-PDF en een overzicht van respons over de gekozen laatste alarmeringen.',
      warning: 'Controleer Rapportstatus vóór verspreiding: een Concept-PDF kan nog worden vernieuwd. De keuze Laatste alarmeringen filtert alleen de statistieken, niet de inzettabel of de vier rapporttellers. Herhaalde alarmeringen aan dezelfde persoon kunnen in statistieken meermaals meetellen.',
    },
  ],
} satisfies ManualGuideMap;
