import type { ManualGuideMap } from '../manualTypes';

export const resourceManualGuides = {
  users: [
    {
      id: 'users-find-open',
      title: 'Een gebruiker zoeken en bekijken',
      intro: 'Open eerst het volledige gebruikersdossier voordat je iets wijzigt.',
      steps: [
        { label: 'Open Gebruikers', description: 'Kies Gebruikers in het menu onder Mensen en middelen.' },
        { label: 'Zoek de juiste persoon', description: 'Gebruik naam, e-mailadres of de gegevens in de tabel om de gebruiker te vinden.' },
        { label: 'Open Details', description: 'Controleer persoonsgegevens, accountstatus, teams, rollen, toestellen, middelen, certificaten en vakanties.' },
        { label: 'Kies pas daarna een actie', description: 'Gebruik Aanpassen of een beheeractie alleen wanneer het dossier bij de bedoelde gebruiker hoort.' },
      ],
      result: 'Je hebt één compleet overzicht van de gebruiker en voorkomt dat je het verkeerde account wijzigt.',
    },
    {
      id: 'users-invite',
      title: 'Een nieuwe gebruiker uitnodigen',
      intro: 'Maak een persoonlijk account en stuur de registratielink naar de gebruiker.',
      permissions: ['users.manage'],
      prerequisites: ['Controleer of de gebruiker nog niet bestaat.', 'Bepaal vooraf welke rollen en teams nodig zijn.'],
      steps: [
        { label: 'Kies Gebruiker aanmaken', description: 'Open Gebruikers en kies bovenaan Gebruiker aanmaken.' },
        { label: 'Vul de persoonsgegevens in', description: 'Voornaam, achternaam en e-mailadres zijn verplicht. Voeg telefoonnummer en woongegevens toe wanneer deze bekend zijn.' },
        { label: 'Kies accountstatus en toestellimiet', description: 'Laat een nieuwe gebruiker normaal op Actief staan en kies hoeveel operator-toestellen deze persoon mag koppelen.' },
        { label: 'Koppel rollen en teams', description: 'Vink alleen de rollen en operationele teams aan die bij het werk van de gebruiker horen.' },
        { label: 'Controleer de uitnodigingsmail', description: 'Laat Welkomstmail sturen en registratie laten afronden aanstaan. Zet je dit uit, dan moet je zelf een geldig tijdelijk wachtwoord invullen.' },
        { label: 'Kies Gebruiker aanmaken', description: 'DIS maakt het account en verstuurt bij de normale route de uitnodiging.' },
      ],
      result: 'De gebruiker kan de uitnodigingslink openen, persoonsgegevens aanvullen, een wachtwoord kiezen en zo nodig MFA instellen.',
      warning: 'De registratielink is 60 minuten geldig. Gebruik Uitnodiging opnieuw versturen wanneer een nog niet gebruikte link is verlopen.',
    },
    {
      id: 'users-edit-access',
      title: 'Gegevens, rollen of teams wijzigen',
      intro: 'Pas een bestaand account aan zonder een tweede gebruiker aan te maken.',
      permissions: ['users.manage'],
      steps: [
        { label: 'Open de gebruiker', description: 'Kies Details en daarna Aanpassen.' },
        { label: 'Werk de basisgegevens bij', description: 'Pas naam, telefoonnummer, woongegevens, accountstatus of het toegestane aantal operator-toestellen aan.' },
        { label: 'Controleer Rollen', description: 'Rollen zijn alleen te wijzigen wanneer je ook Rollen beheren mag gebruiken.' },
        { label: 'Controleer Teams', description: 'Teams zijn alleen te wijzigen wanneer je ook Teams beheren mag gebruiken.' },
        { label: 'Kies Wijzigingen opslaan', description: 'Controleer na opslaan het gebruikersdossier opnieuw.' },
      ],
      result: 'De bijgewerkte persoonsgegevens en toegang zijn direct van kracht.',
      warning: 'Een rol of team verwijderen kan ervoor zorgen dat de gebruiker onderdelen niet meer ziet of niet meer gealarmeerd kan worden.',
    },
    {
      id: 'users-revoke-sessions',
      title: 'Alle sessies van een gebruiker intrekken',
      intro: 'Stop direct de toegang vanuit browsers en gekoppelde mobiele apps.',
      permissions: ['users.manage', 'users.sessions.revoke'],
      steps: [
        { label: 'Open Details', description: 'Controleer naam en e-mailadres van de gebruiker.' },
        { label: 'Ga naar Sessies', description: 'Lees hoeveel actieve web- en mobiele sessies worden geraakt.' },
        { label: 'Kies Sessies intrekken', description: 'Bevestig de actie en wacht op Sessies ingetrokken.' },
        { label: 'Laat opnieuw aanmelden of koppelen', description: 'De gebruiker moet opnieuw inloggen; een ingetrokken mobiele koppeling moet opnieuw worden gemaakt.' },
      ],
      result: 'Bestaande login- en mobiele toegang van deze gebruiker is ongeldig gemaakt.',
      warning: 'Sessies intrekken meldt de gebruiker af op web en gekoppelde mobiele apps. Gebruik dit niet alleen om een pagina te verversen.',
    },
    {
      id: 'users-reset-mfa',
      title: 'MFA van een gebruiker resetten',
      intro: 'Laat tweestapsverificatie opnieuw instellen na verlies van de beveiligingsapp.',
      permissions: ['users.manage', 'users.mfa.reset'],
      steps: [
        { label: 'Open Details', description: 'Controleer dat je de juiste gebruiker hebt.' },
        { label: 'Ga naar MFA herstel', description: 'Kies MFA resetten.' },
        { label: 'Bevestig de reset', description: 'Wacht op de melding dat de bestaande MFA-koppeling is verwijderd.' },
        { label: 'Laat de gebruiker opnieuw inloggen', description: 'De gebruiker moet MFA opnieuw instellen voordat verplichte toegang verdergaat.' },
      ],
      result: 'De oude beveiligingsapp en bestaande sessies zijn niet meer bruikbaar voor dit account.',
      warning: 'Voer dit alleen uit nadat je de identiteit van de gebruiker hebt gecontroleerd.',
    },
    {
      id: 'users-unlock-login',
      title: 'Een tijdelijke inlogblokkade opheffen',
      intro: 'Maak een account eerder toegankelijk na te veel mislukte inlogpogingen.',
      permissions: ['users.manage', 'users.login-lock.reset'],
      steps: [
        { label: 'Open Details', description: 'Controleer accountstatus en de geregistreerde blokkade.' },
        { label: 'Kies Inlogblokkade opheffen', description: 'Gebruik de actie alleen voor de tijdelijke loginbeveiliging.' },
        { label: 'Laat opnieuw inloggen', description: 'Vraag de gebruiker rustig één keer met het juiste wachtwoord en MFA te proberen.' },
      ],
      result: 'De teller voor mislukte loginpogingen is gereset; de gebruiker kan opnieuw proberen in te loggen.',
      warning: 'Dit maakt een account met status Geschorst of Geblokkeerd niet automatisch actief.',
    },
    {
      id: 'users-change-credentials',
      title: 'E-mailadres of wachtwoord wijzigen',
      intro: 'Gebruik dit alleen wanneer de gewone uitnodigings- of herstelroute niet volstaat.',
      permissions: ['users.manage', 'users.credentials.manage'],
      steps: [
        { label: 'Open Details en Aanpassen', description: 'Controleer eerst de identiteit van de gebruiker.' },
        { label: 'Wijzig e-mailadres of wachtwoord', description: 'Laat Wachtwoord leeg wanneer het niet hoeft te veranderen. Een nieuw wachtwoord moet aan het actuele beleid voldoen.' },
        { label: 'Kies Wijzigingen opslaan', description: 'Informeer de gebruiker via een apart veilig kanaal over de wijziging.' },
      ],
      result: 'De nieuwe inloggegevens zijn actief en bestaande sessies zijn ingetrokken.',
      warning: 'Stuur een wachtwoord nooit per gewone e-mail of chat. Gebruik waar mogelijk de uitnodigingsroute waarin de gebruiker zelf een wachtwoord kiest.',
    },
    {
      id: 'users-register-vacation',
      title: 'Vakantie voor een gebruiker vastleggen of intrekken',
      intro: 'Registreer een periode waarin iemand niet inzetbaar mag worden gezet.',
      permissions: ['users.manage'],
      steps: [
        { label: 'Open de gebruiker', description: 'Ga op de gebruikersdetailpagina naar Vakanties.' },
        { label: 'Vul begin en einde in', description: 'Kies de eerste en laatste dag van de vakantie en voeg zo nodig een korte toelichting toe.' },
        { label: 'Sla de vakantie op', description: 'Controleer of de periode in het overzicht verschijnt.' },
        { label: 'Trek zo nodig in', description: 'Gebruik Intrekken wanneer een geplande of actieve vakantie niet meer geldt.' },
      ],
      result: 'Tijdens een actieve vakantie kan de gebruiker niet als beschikbaar worden gezet.',
    },
    {
      id: 'users-resend-invitation',
      title: 'Een verlopen uitnodiging opnieuw versturen',
      intro: 'Maak een nieuwe registratielink voor een actief account dat nog nooit heeft ingelogd.',
      permissions: ['users.manage'],
      steps: [
        { label: 'Open Details', description: 'Zoek de gebruiker en controleer dat het account actief is en nog niet eerder is gebruikt.' },
        { label: 'Ga naar Uitnodiging', description: 'De knop staat alleen bij een gebruiker die de registratie nog niet heeft afgerond.' },
        { label: 'Kies Uitnodiging opnieuw versturen', description: 'Wacht op de bevestiging dat de e-mail opnieuw is verstuurd.' },
        { label: 'Laat de nieuwste link gebruiken', description: 'Vraag de gebruiker oudere uitnodigingsmails te negeren.' },
      ],
      result: 'De gebruiker ontvangt een nieuwe registratielink die 60 minuten geldig is.',
    },
    {
      id: 'users-link-asset',
      title: 'Een bestaand middel aan een gebruiker koppelen',
      intro: 'Koppel een al geregistreerde drone of ander middel aan de juiste eigenaar.',
      permissions: ['assets.view', 'assets.manage'],
      steps: [
        { label: 'Open Details van de gebruiker', description: 'Ga naar het blok Assets.' },
        { label: 'Kies het middel', description: 'Selecteer een bestaande registratie uit de lijst.' },
        { label: 'Kies Koppelen', description: 'Controleer of het middel daarna in het gebruikersdossier staat.' },
        { label: 'Werk gegevens elders bij', description: 'Gebruik Middelen > Aanpassen voor status, serienummer, onderhoud of verwijderen.' },
      ],
      result: 'Het middel is aan deze gebruiker gekoppeld en verschijnt in diens operationele gegevens.',
    },
    {
      id: 'users-link-certification',
      title: 'Een bestaand certificaat aan een gebruiker koppelen',
      intro: 'Koppel de juiste bevoegdheidsregistratie aan de gebruiker.',
      permissions: ['certifications.view', 'certifications.manage'],
      steps: [
        { label: 'Open Details van de gebruiker', description: 'Ga naar het blok Certificaten.' },
        { label: 'Kies het certificaat', description: 'Controleer soort, nummer en verloopdatum voordat je selecteert.' },
        { label: 'Kies Koppelen', description: 'Controleer of het certificaat daarna bij de gebruiker verschijnt.' },
      ],
      result: 'Het gebruikerscertificaat kan meetellen bij inzetcontrole zolang het actief en niet verlopen is.',
    },
    {
      id: 'users-delete',
      title: 'Een gebruiker verwijderen',
      intro: 'Verwijder alleen een account dat echt niet meer gebruikt mag worden.',
      permissions: ['users.delete'],
      prerequisites: ['Controleer of gekoppelde middelen en certificaten niet eerst naar iemand anders moeten.', 'Controleer of je niet je eigen account of de laatste actieve systeembeheerder verwijdert.'],
      steps: [
        { label: 'Open de gebruikerskaart', description: 'Controleer naam, e-mailadres, teams en accountstatus.' },
        { label: 'Kies Verwijderen', description: 'Lees in het bevestigingsvenster welke gekoppelde gegevens verdwijnen.' },
        { label: 'Bevestig Ja, verwijderen', description: 'Wacht totdat je terugkeert naar het gebruikersoverzicht.' },
      ],
      result: 'Het account, planning, actuele koppelingen, middelen en certificaten van de gebruiker zijn verwijderd. Historische namen in incidentrapporten blijven bewaard.',
      warning: 'Verwijderen kan niet ongedaan worden gemaakt. Trek alleen sessies in wanneer het account later nog nodig is.',
    },
  ],
  'address-book': [
    {
      id: 'address-book-search-call',
      title: 'Een contactpersoon zoeken en bellen',
      intro: 'Vind snel een gebruiker op naam, telefoonnummer of woonplaats.',
      steps: [
        { label: 'Open Adresboek', description: 'Kies Adresboek in het menu.' },
        { label: 'Begin direct te typen', description: 'Typ een deel van de naam, het telefoonnummer of de woonplaats. De resultaten worden tijdens het typen aangepast.' },
        { label: 'Controleer de contactregel', description: 'Vergelijk naam en woonplaats voordat je het nummer gebruikt.' },
        { label: 'Klik op het telefoonnummer', description: 'Op een geschikt toestel opent de bel-app met het internationale nummer.' },
      ],
      result: 'Je hebt de juiste contactpersoon gevonden zonder een apart zoekformulier te versturen.',
      warning: 'Het adresboek wordt gevuld vanuit de gebruikerslijst. Wijzig ontbrekende of onjuiste gegevens daarom op de gebruikerskaart.',
    },
  ],
  roles: [
    {
      id: 'roles-create-edit',
      title: 'Een rol maken of aanpassen',
      intro: 'Bundel alleen de rechten die iemand voor een herkenbare taak nodig heeft.',
      prerequisites: ['Schrijf eerst op welke pagina’s en acties bij deze taak horen.', 'Gebruik geen brede beheerrechten wanneer alleen bekijken nodig is.'],
      steps: [
        { label: 'Open Rollen', description: 'Kies Rol toevoegen, of kies Bewerken bij een bestaande rol.' },
        { label: 'Vul Rolcode en Weergavenaam in', description: 'De rolcode wordt een unieke code met kleine letters en streepjes. De weergavenaam beschrijft het werk voor beheerders.' },
        { label: 'Kies app-toegang', description: 'Operator-app geeft toegang tot de operationele mobiele app. Admin-app bepaalt of de rolrechten in de webconsole en mobiele beheerapp gelden.' },
        { label: 'Kies rechten per onderdeel', description: 'Vink bekijken, beheren, verwijderen en gevoelige beheeracties afzonderlijk aan.' },
        { label: 'Controleer de samenvatting', description: 'Loop alle gekozen rechten nog één keer langs en verwijder wat niet nodig is.' },
        { label: 'Kies Rol toevoegen of Rol opslaan', description: 'Koppel de rol daarna via Gebruikers > Aanpassen aan de juiste personen.' },
      ],
      result: 'Gebruikers met deze rol zien alleen de functies waarvoor de rol app-toegang en rechten heeft.',
      warning: 'Je kunt geen rechten doorgeven die je zelf niet hebt. De vaste rol Systeembeheerder kan niet worden aangepast. Een rolwijziging trekt bestaande sessies niet automatisch in.',
    },
    {
      id: 'roles-remove',
      title: 'Een niet meer gebruikte rol verwijderen',
      intro: 'Ruim alleen rollen op die bij geen enkele gebruiker meer horen.',
      permissions: ['roles.delete'],
      steps: [
        { label: 'Controleer gekoppelde gebruikers', description: 'Verwijder de rol eerst bij alle gebruikers die hem nog hebben.' },
        { label: 'Open Rollen', description: 'Zoek de juiste rol en controleer de naam en rechten.' },
        { label: 'Kies Verwijderen', description: 'Lees de bevestiging en controleer nogmaals dat het niet om Systeembeheerder gaat.' },
        { label: 'Bevestig Verwijderen', description: 'De rol verdwijnt uit het overzicht.' },
      ],
      result: 'De ongebruikte rol kan niet meer aan gebruikers worden gekoppeld.',
      warning: 'Een rol met gekoppelde gebruikers kan niet worden verwijderd.',
    },
  ],
  teams: [
    {
      id: 'teams-create-edit',
      title: 'Een operationeel team maken of wijzigen',
      intro: 'Leg vast wie als groep kan worden geselecteerd en welke voorwaarden gelden.',
      steps: [
        { label: 'Open Teams', description: 'Kies Team aanmaken of Aanpassen bij een bestaand team.' },
        { label: 'Vul code, naam en type in', description: 'Gebruik een korte unieke code en een naam die meldkamergebruikers direct herkennen.' },
        { label: 'Kies het ouderteam', description: 'Koppel een subset aan het juiste basisteam. TUI hoort altijd onder OCP.' },
        { label: 'Stel operationeel en mee alarmeren in', description: 'Bepaal of het team actief gebruikt mag worden en welke gekoppelde teams bij alarmering worden meegenomen.' },
        { label: 'Kies vereiste certificaten', description: 'Selecteer alleen certificaten die voor inzet via dit team echt verplicht zijn.' },
        { label: 'Kies Opslaan', description: 'Controleer het team daarna in het overzicht.' },
      ],
      result: 'Het team is beschikbaar voor gebruikersbeheer en, wanneer operationeel, voor incidentalarmering.',
      warning: 'Verander code, type of koppeling van OCP en TUI niet. TUI-leden moeten ook lid van OCP zijn. Mee-alarmeerteams werken één richting en één niveau diep. Zonder gekozen teamcertificaten kunnen certificaatsoorten met Dispatch vereist alsnog als voorwaarde gelden.',
    },
    {
      id: 'teams-manage-members',
      title: 'Leden aan een team toevoegen of verwijderen',
      intro: 'Teamlidmaatschap wordt op de gebruiker beheerd, niet op de teampagina.',
      permissions: ['users.view', 'users.manage'],
      steps: [
        { label: 'Open Gebruikers', description: 'Zoek de persoon die je wilt wijzigen.' },
        { label: 'Kies Details en Aanpassen', description: 'Ga in het gebruikersformulier naar Teams.' },
        { label: 'Vink de juiste teams aan', description: 'Controleer bij TUI dat OCP ook geselecteerd blijft.' },
        { label: 'Kies Wijzigingen opslaan', description: 'Open daarna de gebruiker opnieuw om de koppeling te controleren.' },
      ],
      result: 'De gebruiker telt direct mee voor de gekozen teams en kan alleen volgens de overige inzetvoorwaarden worden gealarmeerd.',
      warning: 'Het gebruikersformulier verstuurt de volledige selectie van rollen en teams. Controleer beide blokken vóór opslaan.',
    },
  ],
  assets: [
    {
      id: 'assets-register-edit',
      title: 'Een middel registreren of bijwerken',
      intro: 'Houd drones, voertuigen en andere inzetmiddelen herkenbaar en actueel.',
      permissions: ['assets.manage'],
      steps: [
        { label: 'Open Middelen', description: 'Kies Asset registreren, of Aanpassen bij een bestaand middel.' },
        { label: 'Kies het soort middel', description: 'Selecteer drone, voertuig of een ander beschikbaar type.' },
        { label: 'Kies bij een drone het dronetype', description: 'Het gekozen merk en model bepaalt welke functies, zoals verlichting of luidspreker, beschikbaar kunnen zijn.' },
        { label: 'Vul herkenbare gegevens in', description: 'Vul naam, serienummer, status, onderhoudsdatum en opmerkingen in voor zover van toepassing.' },
        { label: 'Kies Opslaan', description: 'Controleer daarna de status en eigenaar in het middelenoverzicht.' },
      ],
      result: 'Het middel staat in DIS en kan op een gebruikerskaart aan een gebruiker worden gekoppeld.',
      warning: 'Zet een middel dat niet inzetklaar is niet op Gereed. Beschikbaarheid van middelen telt mee in de operationele beoordeling.',
    },
    {
      id: 'assets-drone-type',
      title: 'Een dronetype toevoegen of aanpassen',
      intro: 'Beheer merk, model en vaste mogelijkheden één keer voor alle drones van dat type.',
      permissions: ['assets.manage'],
      steps: [
        { label: 'Open Drone types', description: 'Kies Drone type toevoegen of Aanpassen bij een bestaand type.' },
        { label: 'Vul fabrikant en model in', description: 'Gebruik de officiële, herkenbare productnaam.' },
        { label: 'Vink de mogelijkheden aan', description: 'Geef aan of het type warmtebeeld, verlichting of een luidspreker ondersteunt.' },
        { label: 'Kies Actief of niet actief', description: 'Zet een type uit wanneer het niet meer voor nieuwe registraties gebruikt mag worden.' },
        { label: 'Kies Opslaan', description: 'Het type is daarna beschikbaar bij drones registreren.' },
      ],
      result: 'Alle drones die dit type gebruiken tonen dezelfde vaste type-eigenschappen zonder technische ID in het label.',
    },
    {
      id: 'assets-delete',
      title: 'Een middel of dronetype verwijderen',
      intro: 'Verwijder alleen een foutieve of definitief afgeschreven registratie.',
      permissions: ['assets.manage'],
      steps: [
        { label: 'Open Aanpassen', description: 'Controleer naam, serienummer, eigenaar en status van het middel.' },
        { label: 'Kies Verwijderen', description: 'Bevestig pas nadat je hebt gecontroleerd dat de registratie niet meer nodig is.' },
        { label: 'Controleer het overzicht', description: 'Het verwijderde middel of type hoort niet meer in de lijst te staan.' },
      ],
      result: 'De actuele registratie is verwijderd.',
      warning: 'Gebruik een niet-actieve status wanneer historische of administratieve herkenning nog nodig is.',
    },
  ],
  certifications: [
    {
      id: 'certifications-read-validity',
      title: 'Controleren of een certificaat geldig is',
      intro: 'Controleer geldigheid voordat je een bevoegdheid voor inzet gebruikt.',
      steps: [
        { label: 'Open Certificaten', description: 'Bekijk bovenaan de gebruikerscertificaten.' },
        { label: 'Zoek de gebruiker en het certificaat', description: 'Controleer naam, soort, nummer, status en verloopdatum.' },
        { label: 'Controleer actief en verloopdatum', description: 'Een certificaat telt alleen mee wanneer het actief is en nog niet is verlopen.' },
        { label: 'Open zo nodig de gebruiker', description: 'Koppelen of verlengen gebeurt vanuit het gebruikersdossier wanneer je daarvoor rechten hebt.' },
      ],
      result: 'Je weet of het certificaat op dit moment voor inzet mag meetellen.',
    },
    {
      id: 'certifications-manage-type',
      title: 'Een certificaatsoort maken of aanpassen',
      intro: 'Leg de soort en de gevolgen voor inzet centraal vast.',
      permissions: ['certifications.manage'],
      steps: [
        { label: 'Open Certificaatsoorten', description: 'Kies Certificaat aanmaken of Aanpassen bij een bestaande soort.' },
        { label: 'Vul code en naam in', description: 'Gebruik een unieke code en een naam die beheerders en operators begrijpen.' },
        { label: 'Kies Dispatch vereist', description: 'Vink dit alleen aan wanneer een geldig certificaat echt een voorwaarde voor alarmering is.' },
        { label: 'Vul de omschrijving in', description: 'Leg kort uit waarvoor het certificaat geldt.' },
        { label: 'Kies Opslaan', description: 'De soort kan daarna bij teams en gebruikers worden gebruikt.' },
      ],
      result: 'De certificaatsoort is centraal beschikbaar en kan de inzetgeschiktheid beïnvloeden.',
      warning: 'Certificaatsoorten kunnen op deze pagina niet worden verwijderd. Pas Dispatch vereist alleen aan na operationele controle.',
    },
  ],
  expiry: [
    {
      id: 'expiry-review',
      title: 'Aankomend verloop controleren',
      intro: 'Plan onderhoud en verlenging voordat iemand of iets niet meer inzetbaar is.',
      steps: [
        { label: 'Open Verloop', description: 'Kies Verloop onder Mensen en middelen.' },
        { label: 'Kies de vooruitblik', description: 'Selecteer 30, 60, 90 of 180 dagen.' },
        { label: 'Begin bij Kritiek', description: 'Kritiek betekent al verlopen of binnen zeven dagen. Handel deze regels eerst af.' },
        { label: 'Controleer Binnen 30 dagen en Later', description: 'Plan verlenging of onderhoud ruim vóór de vermelde datum.' },
        { label: 'Open het juiste beheeronderdeel', description: 'Werk het middel bij onder Middelen of het gebruikerscertificaat via de betreffende gebruiker.' },
      ],
      result: 'Je hebt een praktische werklijst voor onderhoud en certificaatverlenging.',
      warning: 'Verloop is een alleen-lezen overzicht. Een regel verdwijnt pas nadat de brongegevens zijn bijgewerkt.',
    },
  ],
} satisfies ManualGuideMap;
